// THIS FILE IS AUTOGENERATED BY PATCH. See patch instructions.
"use client";

import { useMemo, useState } from "react";

type MCQ = {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

type InputQ = {
  id: string;
  prompt: string; // with ____ gap
  correct: string; // normalized expected answer
  explanation: string;
};

type ExerciseSet =
  | { type: "mcq"; title: string; instructions: string; questions: MCQ[] }
  | { type: "input"; title: string; instructions: string; questions: InputQ[] };

function normalize(s: string) {
  return s.trim().toLowerCase();
}

export default function ThereIsThereAreLessonClient() {
  const [tab, setTab] = useState<"exercises" | "explanation">("exercises");
  const [exNo, setExNo] = useState<1 | 2 | 3 | 4>(1);
  const [checked, setChecked] = useState(false);

  const sets: Record<1 | 2 | 3 | 4, ExerciseSet> = useMemo(() => {
    return {
      // EX 1: easiest, MCQ
      1: {
        type: "mcq",
        title: "Exercise 1 (Easy) — Choose the correct option",
        instructions: "Choose There is or There are.",
        questions: [
          {
            id: "e1q1",
            prompt: "_____ a café near here.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Use There is with singular: a café.",
          },
          {
            id: "e1q2",
            prompt: "_____ two windows in the room.",
            options: ["There is", "There are"],
            correctIndex: 1,
            explanation: "Use There are with plural: two windows.",
          },
          {
            id: "e1q3",
            prompt: "_____ a lot of traffic today.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Traffic is uncountable → There is.",
          },
          {
            id: "e1q4",
            prompt: "_____ five students in my class.",
            options: ["There is", "There are"],
            correctIndex: 1,
            explanation: "Plural noun (students) → There are.",
          },
          {
            id: "e1q5",
            prompt: "_____ a problem with the Wi‑Fi.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Singular: a problem → There is.",
          },
          {
            id: "e1q6",
            prompt: "_____ some milk in the fridge.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Milk is uncountable → There is.",
          },
          {
            id: "e1q7",
            prompt: "_____ three chairs in the kitchen.",
            options: ["There is", "There are"],
            correctIndex: 1,
            explanation: "Plural (chairs) → There are.",
          },
          {
            id: "e1q8",
            prompt: "_____ an email for you.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Singular: an email → There is.",
          },
          {
            id: "e1q9",
            prompt: "_____ many parks in this city.",
            options: ["There is", "There are"],
            correctIndex: 1,
            explanation: "Plural (parks) → There are.",
          },
          {
            id: "e1q10",
            prompt: "_____ a bank next to the supermarket.",
            options: ["There is", "There are"],
            correctIndex: 0,
            explanation: "Singular: a bank → There is.",
          },
        ],
      },

      // EX 2: fill in there is/there are
      2: {
        type: "input",
        title: "Exercise 2 (Medium) — Type the missing words",
        instructions: "Write there is or there are. (No punctuation needed.)",
        questions: [
          {
            id: "e2q1",
            prompt: "_____ a TV in the living room.",
            correct: "there is",
            explanation: "Singular: a TV → there is.",
          },
          {
            id: "e2q2",
            prompt: "_____ two bathrooms in the apartment.",
            correct: "there are",
            explanation: "Plural: two bathrooms → there are.",
          },
          {
            id: "e2q3",
            prompt: "_____ a new student in our group.",
            correct: "there is",
            explanation: "Singular: a new student → there is.",
          },
          {
            id: "e2q4",
            prompt: "_____ many shops on this street.",
            correct: "there are",
            explanation: "Plural: many shops → there are.",
          },
          {
            id: "e2q5",
            prompt: "_____ a message from your teacher.",
            correct: "there is",
            explanation: "Singular: a message → there is.",
          },
          {
            id: "e2q6",
            prompt: "_____ three dogs in the park.",
            correct: "there are",
            explanation: "Plural: three dogs → there are.",
          },
          {
            id: "e2q7",
            prompt: "_____ a bus stop in front of the hotel.",
            correct: "there is",
            explanation: "Singular: a bus stop → there is.",
          },
          {
            id: "e2q8",
            prompt: "_____ a lot of noise outside.",
            correct: "there is",
            explanation: "Noise is uncountable → there is.",
          },
          {
            id: "e2q9",
            prompt: "_____ four pictures on the wall.",
            correct: "there are",
            explanation: "Plural: four pictures → there are.",
          },
          {
            id: "e2q10",
            prompt: "_____ some bread on the table.",
            correct: "there is",
            explanation: "Bread is uncountable → there is.",
          },
        ],
      },

      // EX 3: negatives (isn't / aren't)
      3: {
        type: "input",
        title: "Exercise 3 (Hard) — Negatives",
        instructions:
          "Write there isn't / there aren't. Use: there isn't (singular/uncountable) and there aren't (plural).",
        questions: [
          {
            id: "e3q1",
            prompt: "_____ a hospital in my town.",
            correct: "there isn't",
            explanation: "Singular: a hospital → there isn't.",
          },
          {
            id: "e3q2",
            prompt: "_____ any chairs in this room.",
            correct: "there aren't",
            explanation: "Plural: chairs → there aren't.",
          },
          {
            id: "e3q3",
            prompt: "_____ a bus today.",
            correct: "there isn't",
            explanation: "Singular: a bus → there isn't.",
          },
          {
            id: "e3q4",
            prompt: "_____ any milk in the fridge.",
            correct: "there isn't",
            explanation: "Milk is uncountable → there isn't.",
          },
          {
            id: "e3q5",
            prompt: "_____ two keys on the table.",
            correct: "there aren't",
            explanation: "Plural: two keys → there aren't.",
          },
          {
            id: "e3q6",
            prompt: "_____ a good restaurant near here.",
            correct: "there isn't",
            explanation: "Singular: a restaurant → there isn't.",
          },
          {
            id: "e3q7",
            prompt: "_____ any students in the classroom.",
            correct: "there aren't",
            explanation: "Plural: students → there aren't.",
          },
          {
            id: "e3q8",
            prompt: "_____ a window in the bathroom.",
            correct: "there isn't",
            explanation: "Singular: a window → there isn't.",
          },
          {
            id: "e3q9",
            prompt: "_____ any books on the shelf.",
            correct: "there aren't",
            explanation: "Plural: books → there aren't.",
          },
          {
            id: "e3q10",
            prompt: "_____ five people in the car.",
            correct: "there aren't",
            explanation: "Plural: five people → there aren't.",
          },
        ],
      },

      // EX 4: questions (is there / are there)
      4: {
        type: "input",
        title: "Exercise 4 (Harder) — Questions",
        instructions:
          "Write is there or are there. (No punctuation needed.)",
        questions: [
          {
            id: "e4q1",
            prompt: "_____ a pharmacy near here?",
            correct: "is there",
            explanation: "Singular: a pharmacy → Is there…?",
          },
          {
            id: "e4q2",
            prompt: "_____ any eggs in the fridge?",
            correct: "are there",
            explanation: "Plural: eggs → Are there…?",
          },
          {
            id: "e4q3",
            prompt: "_____ a cinema in this area?",
            correct: "is there",
            explanation: "Singular: a cinema → Is there…?",
          },
          {
            id: "e4q4",
            prompt: "_____ any free seats?",
            correct: "are there",
            explanation: "Plural: seats → Are there…?",
          },
          {
            id: "e4q5",
            prompt: "_____ a toilet on this floor?",
            correct: "is there",
            explanation: "Singular: a toilet → Is there…?",
          },
          {
            id: "e4q6",
            prompt: "_____ any children in the park?",
            correct: "are there",
            explanation: "Plural: children → Are there…?",
          },
          {
            id: "e4q7",
            prompt: "_____ a problem with your order?",
            correct: "is there",
            explanation: "Singular: a problem → Is there…?",
          },
          {
            id: "e4q8",
            prompt: "_____ any clean glasses?",
            correct: "are there",
            explanation: "Plural: glasses → Are there…?",
          },
          {
            id: "e4q9",
            prompt: "_____ a good reason to worry?",
            correct: "is there",
            explanation: "Singular: a reason → Is there…?",
          },
          {
            id: "e4q10",
            prompt: "_____ any messages for me?",
            correct: "are there",
            explanation: "Plural: messages → Are there…?",
          },
        ],
      },
    };
  }, []);

  // Store answers
  const [mcqAnswers, setMcqAnswers] = useState<Record<string, number | null>>({});
  const [inputAnswers, setInputAnswers] = useState<Record<string, string>>({});

  const current = sets[exNo];

  const score = useMemo(() => {
    if (!checked) return null;

    let correct = 0;
    let total = 0;

    if (current.type === "mcq") {
      total = current.questions.length;
      for (const q of current.questions) {
        const a = mcqAnswers[q.id];
        if (a === q.correctIndex) correct++;
      }
    } else {
      total = current.questions.length;
      for (const q of current.questions) {
        const a = normalize(inputAnswers[q.id] ?? "");
        if (a && a === normalize(q.correct)) correct++;
      }
    }

    const percent = total ? Math.round((correct / total) * 100) : 0;
    return { correct, total, percent };
  }, [checked, current, mcqAnswers, inputAnswers]);

  function resetExercise() {
    window.scrollTo({ top: 0, behavior: "smooth" });
    setChecked(false);
    setMcqAnswers({});
    setInputAnswers({});
  }

  function switchExercise(n: 1 | 2 | 3 | 4) {
    window.scrollTo({ top: 0, behavior: "smooth" });
    setExNo(n);
    setChecked(false);
    setMcqAnswers({});
    setInputAnswers({});
  }

  return (
    <div className="relative min-h-screen w-full">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-[#FFF7D9] via-white to-white" />
      <div className="pointer-events-none absolute -top-28 left-1/2 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-[#F5DA20]/20 blur-3xl" />
      <div className="relative mx-auto max-w-7xl px-6 py-10">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-slate-500">
        <a className="hover:text-slate-900 transition" href="/">Home</a>
        <span className="text-slate-300">/</span>
        <a className="hover:text-slate-900 transition" href="/grammar/a1">Grammar A1</a>
        <span className="text-slate-300">/</span>
        <span className="text-slate-700 font-medium">There is / There are</span>
      </div>

      <div className="mt-4 flex flex-wrap items-start gap-3">
        <h1 className="text-3xl md:text-5xl font-black tracking-tight text-slate-900 leading-tight">
          There is / There are <span className="font-extrabold">— basics</span>
        </h1>
        <span className="mt-2 inline-flex items-center rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700 border border-emerald-200">
          A1
        </span>
      </div>

      <p className="mt-3 max-w-3xl text-slate-700">
        Use <b>There is</b> / <b>There are</b> to say that something exists in a place. Practice with 4 graded exercises.
      </p>

      {/* Layout: left ad + center content + right ad */}
      <div className="mt-10 grid gap-8 lg:grid-cols-[300px_1fr_300px] lg:items-start">
        {/* Left Ad */}
        <aside className="hidden lg:block lg:sticky lg:top-24 lg:self-start lg:h-fit">
          <div className="rounded-2xl border border-black/10 bg-white/60 backdrop-blur p-4">
            <div className="text-xs font-semibold text-slate-500">ADVERTISEMENT</div>
            <div className="mt-3 h-[600px] rounded-xl border border-black/10 bg-white flex items-center justify-center text-slate-400 text-sm">
              300 × 600
            </div>
          </div>
        </aside>

        {/* Center */}
        <section className="rounded-2xl border border-black/10 bg-white/70 backdrop-blur overflow-hidden">
          {/* Tabs */}
          <div className="flex items-center gap-2 border-b border-black/10 bg-white/60 p-3">
            <button
              onClick={() => setTab("exercises")}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition ${
                tab === "exercises" ? "bg-[#F5DA20] text-black" : "text-slate-700 hover:bg-black/5"
              }`}
            >
              Exercises
            </button>
            <button
              onClick={() => setTab("explanation")}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition ${
                tab === "explanation" ? "bg-[#F5DA20] text-black" : "text-slate-700 hover:bg-black/5"
              }`}
            >
              Explanation
            </button>

            <div className="ml-auto hidden sm:flex items-center gap-2 text-sm text-slate-600">
              Exercises:
              {[1, 2, 3, 4].map((n) => (
                <button
                  key={n}
                  onClick={() => switchExercise(n as 1 | 2 | 3 | 4)}
                  className={`h-9 w-9 rounded-xl border border-black/10 font-bold transition ${
                    exNo === n ? "bg-[#F5DA20] text-black" : "bg-white text-slate-800 hover:bg-black/5"
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="p-6 md:p-8">
            {tab === "exercises" ? (
              <>
                <div className="flex flex-col gap-2">
                  <h2 className="text-2xl font-black text-slate-900">{current.title}</h2>
                  <p className="text-slate-700">{current.instructions}</p>

                  {/* Mobile exercise buttons */}
                  <div className="mt-2 flex sm:hidden items-center gap-2 text-sm text-slate-600">
                    <span>Exercises:</span>
                    {[1, 2, 3, 4].map((n) => (
                      <button
                        key={n}
                        onClick={() => switchExercise(n as 1 | 2 | 3 | 4)}
                        className={`h-9 w-9 rounded-xl border border-black/10 font-bold transition ${
                          exNo === n ? "bg-[#F5DA20] text-black" : "bg-white text-slate-800 hover:bg-black/5"
                        }`}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Questions */}
                <div className="mt-8 space-y-5">
                  {current.type === "mcq" ? (
                    current.questions.map((q, idx) => {
                      const chosen = mcqAnswers[q.id] ?? null;
                      const isCorrect = checked && chosen === q.correctIndex;
                      const isWrong = checked && chosen !== null && chosen !== q.correctIndex;
                      const noAnswer = checked && chosen === null;

                      return (
                        <div key={q.id} className="rounded-2xl border border-black/10 bg-white p-5">
                          <div className="flex items-start gap-3">
                            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-black/5 text-sm font-black text-slate-700">
                              {idx + 1}
                            </div>
                            <div className="flex-1">
                              <div className="font-bold text-slate-900">{q.prompt}</div>

                              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                                {q.options.map((opt, oi) => (
                                  <label
                                    key={oi}
                                    className={`flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2 transition ${
                                      chosen === oi
                                        ? "border-[#F5DA20] bg-[#F5DA20]/20"
                                        : "border-black/10 bg-white hover:bg-black/5"
                                    } ${checked ? "cursor-default opacity-95" : ""}`}
                                  >
                                    <input
                                      type="radio"
                                      name={q.id}
                                      disabled={checked}
                                      checked={chosen === oi}
                                      onChange={() => setMcqAnswers((p) => ({ ...p, [q.id]: oi }))}
                                    />
                                    <span className="text-slate-900">{opt}</span>
                                  </label>
                                ))}
                              </div>

                              {checked && (
                                <div className="mt-3 text-sm">
                                  {isCorrect && <div className="text-emerald-700 font-semibold">✅ Correct</div>}
                                  {isWrong && <div className="text-red-700 font-semibold">❌ Wrong</div>}
                                  {noAnswer && <div className="text-amber-700 font-semibold">⚠ No answer</div>}

                                  <div className="mt-2 text-slate-700">
                                    <b className="text-slate-900">Correct:</b> {q.options[q.correctIndex]} — {q.explanation}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })
                  ) : (
                    current.questions.map((q, idx) => {
                      const val = inputAnswers[q.id] ?? "";
                      const answered = normalize(val) !== "";
                      const isCorrect = checked && answered && normalize(val) === normalize(q.correct);
                      const noAnswer = checked && !answered;
                      const wrong = checked && answered && !isCorrect;

                      return (
                        <div key={q.id} className="rounded-2xl border border-black/10 bg-white p-5">
                          <div className="flex items-start gap-3">
                            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-black/5 text-sm font-black text-slate-700">
                              {idx + 1}
                            </div>

                            <div className="flex-1">
                              <div className="font-bold text-slate-900">{q.prompt}</div>

                              <div className="mt-3 flex items-center gap-3">
                                <input
                                  value={val}
                                  disabled={checked}
                                  onChange={(e) => setInputAnswers((p) => ({ ...p, [q.id]: e.target.value }))}
                                  placeholder="Type here…"
                                  className="w-full max-w-xs rounded-xl border border-black/10 bg-white px-4 py-3 text-slate-900 placeholder:text-slate-400 outline-none focus:border-[#F5DA20]"
                                />
                              </div>

                              {checked && (
                                <div className="mt-3 text-sm">
                                  {isCorrect && <div className="text-emerald-700 font-semibold">✅ Correct</div>}
                                  {wrong && <div className="text-red-700 font-semibold">❌ Wrong</div>}
                                  {noAnswer && <div className="text-amber-700 font-semibold">⚠ No answer</div>}

                                  <div className="mt-2 text-slate-700">
                                    <b className="text-slate-900">Correct:</b> {q.correct} — {q.explanation}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>

                {/* Controls */}
                <div className="mt-8 space-y-4">
                  <div className="flex flex-wrap gap-3 items-center">
                    {!checked ? (
                      <button
                        onClick={() => { setChecked(true); window.scrollTo({ top: 0, behavior: "smooth" }); }}
                        className="rounded-2xl bg-[#F5DA20] px-6 py-3 text-sm font-black text-black hover:opacity-90 transition shadow-sm"
                      >
                        Check Answers
                      </button>
                    ) : (
                      <button
                        onClick={resetExercise}
                        className="rounded-2xl border border-black/10 bg-white px-6 py-3 text-sm font-bold text-slate-900 hover:bg-black/5 transition"
                      >
                        Try Again
                      </button>
                    )}
                    {checked && exNo < 4 && (
                      <button
                        onClick={() => switchExercise((exNo + 1) as 1 | 2 | 3 | 4)}
                        className="rounded-2xl border border-black/10 bg-white px-6 py-3 text-sm font-bold text-slate-700 hover:bg-black/5 transition"
                      >
                        Next Exercise →
                      </button>
                    )}
                  </div>

                  {score && (
                    <div className={`rounded-2xl border p-4 ${
                      score.percent >= 80
                        ? "border-emerald-200 bg-emerald-50"
                        : score.percent >= 50
                        ? "border-amber-200 bg-amber-50"
                        : "border-red-200 bg-red-50"
                    }`}>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className={`text-3xl font-black ${
                            score.percent >= 80 ? "text-emerald-700" : score.percent >= 50 ? "text-amber-700" : "text-red-700"
                          }`}>
                            {score.percent}%
                          </div>
                          <div className="mt-0.5 text-sm text-slate-600">
                            {score.correct} out of {score.total} correct
                          </div>
                        </div>
                        <div className="text-3xl">
                          {score.percent >= 80 ? "🎉" : score.percent >= 50 ? "💪" : "📖"}
                        </div>
                      </div>
                      <div className="mt-3 h-2 w-full rounded-full bg-black/10 overflow-hidden">
                        <div
                          className={`h-2 rounded-full transition-all duration-500 ${
                            score.percent >= 80 ? "bg-emerald-500" : score.percent >= 50 ? "bg-amber-500" : "bg-red-500"
                          }`}
                          style={{ width: `${score.percent}%` }}
                        />
                      </div>
                      <div className="mt-2 text-xs text-slate-500">
                        {score.percent >= 80
                          ? "Excellent! You can move to the next exercise."
                          : score.percent >= 50
                          ? "Good effort! Try once more to improve your score."
                          : "Keep practising — review the Explanation tab and try again."}
                      </div>
                    </div>
                  )}
                </div>
              </>
            ) : (
              <Explanation />
            )}
          </div>
        </section>

        {/* Right Ad */}
        <aside className="hidden lg:block lg:sticky lg:top-24 lg:self-start lg:h-fit">
          <div className="rounded-2xl border border-black/10 bg-white/60 backdrop-blur p-4">
            <div className="text-xs font-semibold text-slate-500">ADVERTISEMENT</div>
            <div className="mt-3 h-[600px] rounded-xl border border-black/10 bg-white flex items-center justify-center text-slate-400 text-sm">
              300 × 600
            </div>
          </div>
        </aside>
      </div>

      {/* Bottom navigation */}
      <div className="mt-10 flex items-center justify-between gap-4 border-t border-black/8 pt-8">
        <a
          href="/grammar/a1"
          className="flex items-center gap-2 rounded-2xl border border-black/10 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-black/5 transition"
        >
          ← All A1 topics
        </a>
        <a
          href="/grammar/a1/articles-a-an"
          className="flex items-center gap-2 rounded-2xl bg-[#F5DA20] px-5 py-3 text-sm font-black text-black hover:opacity-90 transition shadow-sm"
        >
          Next: Articles: a / an →
        </a>
      </div>
      </div>
    </div>
  );
}

function Formula({ parts }: { parts: Array<{ text?: string; color?: string; dim?: boolean }> }) {
  const colors: Record<string, string> = {
    sky:    "bg-sky-100 text-sky-800 border-sky-200",
    yellow: "bg-[#FFF3A3] text-amber-800 border-amber-300",
    red:    "bg-red-100 text-red-800 border-red-200",
    violet: "bg-violet-100 text-violet-800 border-violet-200",
    green:  "bg-emerald-100 text-emerald-800 border-emerald-200",
    slate:  "bg-slate-100 text-slate-600 border-slate-200",
  };
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      {parts.map((p, i) =>
        p.dim ? (
          <span key={i} className="text-slate-400 font-bold text-sm">+</span>
        ) : (
          <span key={i} className={`rounded-lg px-2.5 py-1 text-xs font-black border ${p.color ? colors[p.color] : colors.slate}`}>
            {p.text}
          </span>
        )
      )}
    </div>
  );
}

function Ex({ en, correct = true }: { en: string; correct?: boolean }) {
  return (
    <div className={`flex items-start gap-2 rounded-xl px-3 py-2.5 ${correct ? "bg-white border border-black/8" : "bg-red-50 border border-red-100"}`}>
      <span className="text-sm shrink-0">{correct ? "✅" : "❌"}</span>
      <div className={`font-semibold text-sm ${correct ? "text-slate-900" : "text-red-700 line-through"}`}>{en}</div>
    </div>
  );
}

function Explanation() {
  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-black text-slate-900 mb-1">There is / There are</h2>
        <p className="text-slate-500 text-sm">Use these to say that something exists or is present somewhere.</p>
      </div>

      {/* Affirmative card */}
      <div className="rounded-2xl border border-emerald-200 bg-gradient-to-b from-emerald-50 to-white p-5 space-y-3">
        <div className="text-xs font-black uppercase tracking-widest text-emerald-700">Affirmative</div>
        <Formula parts={[
          { text: "There is / There are", color: "green" },
          { dim: true },
          { text: "noun phrase", color: "sky" },
        ]} />
        <div className="grid gap-2 md:grid-cols-2 pt-1">
          <Ex en="There is a café near here." />
          <Ex en="There are two chairs in the room." />
          <Ex en="There is some milk in the fridge." />
          <Ex en="There are many parks in this city." />
        </div>
      </div>

      {/* Negative card */}
      <div className="rounded-2xl border border-red-200 bg-gradient-to-b from-red-50 to-white p-5 space-y-3">
        <div className="text-xs font-black uppercase tracking-widest text-red-600">Negative</div>
        <Formula parts={[
          { text: "There isn't / There aren't", color: "red" },
          { dim: true },
          { text: "noun phrase", color: "sky" },
        ]} />
        <div className="grid gap-2 md:grid-cols-2 pt-1">
          <Ex en="There isn't a bus today." />
          <Ex en="There aren't any seats." />
          <Ex en="There isn't any milk." />
          <Ex en="There aren't any problems." />
        </div>
      </div>

      {/* Question card */}
      <div className="rounded-2xl border border-sky-200 bg-gradient-to-b from-sky-50 to-white p-5 space-y-3">
        <div className="text-xs font-black uppercase tracking-widest text-sky-700">Question</div>
        <Formula parts={[
          { text: "Is / Are", color: "sky" },
          { dim: true },
          { text: "there", color: "violet" },
          { dim: true },
          { text: "noun phrase", color: "sky" },
          { dim: true },
          { text: "?", color: "slate" },
        ]} />
        <div className="grid gap-2 md:grid-cols-2 pt-1">
          <Ex en="Is there a bank near here?" />
          <Ex en="Are there any eggs?" />
          <Ex en="Is there any water?" />
          <Ex en="Are there any hotels here?" />
        </div>
        <div className="text-xs text-slate-500 pt-1 font-semibold">Short answers: Yes, there is. / No, there isn't. / Yes, there are. / No, there aren't.</div>
      </div>

      {/* Reference table */}
      <div className="rounded-2xl border border-black/10 bg-white p-5">
        <div className="flex items-center gap-2 mb-4">
          <span className="flex h-6 w-6 items-center justify-center rounded-full bg-yellow-400 text-xs font-black text-white">!</span>
          <span className="text-sm font-black text-slate-700 uppercase tracking-wide">Singular vs Plural — quick reference</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b border-black/10">
                <th className="py-2 pr-4 text-left text-xs font-black text-slate-500 uppercase">Form</th>
                <th className="py-2 pr-4 text-left text-xs font-black text-slate-500 uppercase">✅ Positive</th>
                <th className="py-2 pr-4 text-left text-xs font-black text-slate-500 uppercase">❌ Negative</th>
                <th className="py-2 text-left text-xs font-black text-slate-500 uppercase">❓ Question</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              <tr>
                <td className="py-2.5 pr-4 font-black text-slate-700">Singular</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>is</strong> a cat.</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>isn't</strong> a cat.</td>
                <td className="py-2.5 text-slate-700"><strong>Is there</strong> a cat?</td>
              </tr>
              <tr>
                <td className="py-2.5 pr-4 font-black text-slate-700">Uncountable</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>is</strong> water.</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>isn't</strong> any water.</td>
                <td className="py-2.5 text-slate-700"><strong>Is there</strong> any water?</td>
              </tr>
              <tr>
                <td className="py-2.5 pr-4 font-black text-slate-700">Plural</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>are</strong> cats.</td>
                <td className="py-2.5 pr-4 text-slate-700">There <strong>aren't</strong> any cats.</td>
                <td className="py-2.5 text-slate-700"><strong>Are there</strong> any cats?</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Amber warning */}
      <div className="rounded-xl bg-amber-50 border border-amber-200 px-4 py-3 text-sm text-amber-800">
        <span className="font-black">Warning:</span> Never use <strong>There is</strong> with a plural noun.
        <div className="mt-2 space-y-1">
          <Ex en="There are three cats in the garden." />
          <Ex en="There is three cats in the garden." correct={false} />
        </div>
      </div>
    </div>
  );
}