import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const FUTPERF_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "By 6 PM, she ___ finished all her work.", options: ["will have", "won't have", "will has", "have will"], answer: 0 },
  { q: "Future Perfect = will have + ___", options: ["base verb", "verb-ing", "past participle", "to + verb"], answer: 2 },
  { q: "By the time you arrive, I ___ cooked dinner.", options: ["will have", "won't have", "will be", "have"], answer: 0 },
  { q: "She ___ finished the report by Friday — she needs more time.", options: ["will have", "won't have", "will be", "has"], answer: 1 },
  { q: "___ you have finished by tomorrow?", options: ["Are", "Do", "Will", "Have"], answer: 2 },
  { q: "go → past participle: ___", options: ["went", "goes", "gone", "going"], answer: 2 },
  { q: "eat → past participle: ___", options: ["ate", "eaten", "eating", "eats"], answer: 1 },
  { q: "write → past participle: ___", options: ["wrote", "writing", "written", "writes"], answer: 2 },
  { q: "By next year, they ___ built the new stadium.", options: ["will have", "won't have", "will be", "have"], answer: 0 },
  { q: "\"Will you have finished?\" — \"Yes, ___.\"", options: ["I do", "I will", "I have", "I will have"], answer: 1 },
  { q: "\"Will she have left?\" — \"No, ___.\"", options: ["she won't", "she doesn't", "she isn't", "she won't have"], answer: 0 },
  { q: "By the time + Present Simple = ___ in the other clause.", options: ["Future Simple", "Future Perfect", "Past Simple", "Present Perfect"], answer: 1 },
  { q: "He ___ forgotten about it by tomorrow.", options: ["will have", "won't have", "will be", "has"], answer: 0 },
  { q: "build → past participle: ___", options: ["builded", "built", "building", "builds"], answer: 1 },
  { q: "By Monday, the team ___ completed the project.", options: ["will have", "won't have", "will be", "are going to"], answer: 0 },
  { q: "I'm afraid they ___ read the report by Monday.", options: ["will have", "won't have", "will be", "have"], answer: 1 },
  { q: "By the end of the month, he ___ spent all his savings.", options: ["will have", "won't have", "will be", "has"], answer: 0 },
  { q: "leave → past participle: ___", options: ["leaved", "leaving", "left", "lefted"], answer: 2 },
  { q: "We ___ eaten by the time they arrive — dinner isn't ready.", options: ["will have", "won't have", "will be", "are going to have"], answer: 1 },
  { q: "make → past participle: ___", options: ["maked", "making", "makes", "made"], answer: 3 },
];

export const FUTPERF_PDF_CONFIG: LessonPDFConfig = {
  title: "Future Perfect",
  subtitle: "Completed actions before a future deadline — 4 exercises + answer key",
  level: "B2",
  keyRule: "Subject + will have + past participle  →  By Friday she will have finished the project.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the affirmative Future Perfect form (will have + past participle).",
      hint: "will have + past participle",
      questions: [
        "By 6 PM, she ___ (finish) all her work.",
        "By the time you arrive, I ___ (cook) dinner.",
        "By next year, they ___ (build) the new stadium.",
        "He ___ (forget) about it by tomorrow.",
        "By the time the film starts, we ___ (eat).",
        "By Monday, the team ___ (complete) the project.",
        "She ___ (leave) by the time you get there.",
        "By next week, I ___ (read) the whole novel.",
        "By the end of the month, he ___ (spend) all his savings.",
        "By the time you call, they ___ (make) a decision.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Easy",
      instruction: "Write the negative Future Perfect form (won't have + past participle).",
      hint: "won't have + past participle",
      questions: [
        "She ___ (finish) the report by Friday — she needs more time.",
        "I ___ (complete) the course by summer — it's too long.",
        "They ___ (arrive) by 8 PM — they left too late.",
        "He ___ (save) enough money by then.",
        "We ___ (eat) by the time they get here — dinner isn't ready.",
        "By Monday, she ___ (read) all the documents.",
        "By next year, they ___ (sell) the house yet.",
        "I ___ (write) the letter by this afternoon.",
        "He ___ (learn) all the vocabulary by the test.",
        "By next week, she ___ (recover) from her illness.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write the Future Perfect question (Will + subject + have + past participle?).",
      hint: "Will + subject + have + pp?",
      questions: [
        "___ (you / finish) by tomorrow? (finish)",
        "___ (she / leave) by the time we arrive? (leave)",
        "___ (they / complete) the project by Friday? (complete)",
        "___ (he / eat) by the time we get there? (eat)",
        "___ (the team / build) the bridge by 2030? (build)",
        "\"Will you have finished?\" — \"Yes, ___\"",
        "\"Will she have left?\" — \"No, ___\"",
        "\"Will they have arrived?\" — \"Yes, ___\"",
        "\"Will he have called?\" — \"No, ___\"",
        "\"Will it have stopped raining?\" — \"Yes, ___\"",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Mixed Future Perfect — affirmative, negative, or question. Also decide: Future Simple or Future Perfect?",
      questions: [
        "By the time you wake up, I ___ (already / leave).",
        "She ___ (not / finish) by Friday — she just started.",
        "___ (he / read) the email by the time the meeting starts?",
        "I ___ (call) you when I'm ready. (single action)",
        "By noon, I ___ (call) you three times already.",
        "She ___ (arrive) at 6 PM. (scheduled event)",
        "By 6 PM, she ___ (arrive) already.",
        "Don't worry — they ___ (make) a decision by then.",
        "He ___ (probably / not / pass) the exam — he hasn't studied.",
        "By the end of the course, we ___ (study) all 12 tenses.",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — will have + past participle",
      answers: ["will have finished", "will have cooked", "will have built", "will have forgotten", "will have eaten", "will have completed", "will have left", "will have read", "will have spent", "will have made"],
    },
    {
      exercise: 2,
      subtitle: "Easy — won't have + past participle",
      answers: ["won't have finished", "won't have completed", "won't have arrived", "won't have saved", "won't have eaten", "won't have read", "won't have sold", "won't have written", "won't have learned", "won't have recovered"],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions and short answers",
      answers: ["Will you have finished by tomorrow?", "Will she have left by the time we arrive?", "Will they have completed the project?", "Will he have eaten by the time we get there?", "Will the team have built the bridge by 2030?", "Yes, I will.", "No, she won't.", "Yes, they will.", "No, he won't.", "Yes, it will."],
    },
    {
      exercise: 4,
      subtitle: "Hard — mixed Future Perfect",
      answers: ["will have already left", "won't have finished", "Will he have read the email?", "will call", "will have called", "will arrive", "will have already arrived", "will have made", "probably won't have passed", "will have studied"],
    },
  ],
};
