import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PASTPERFCONT_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "She ___ waiting for an hour when he arrived.", options: ["has been", "was", "had been", "had"], answer: 2 },
  { q: "They ___ running for 20 minutes when it rained.", options: ["have been", "were", "had been", "had"], answer: 2 },
  { q: "He ___ studying all night, so he was exhausted.", options: ["has been", "was", "had been", "did"], answer: 2 },
  { q: "___ she working before you called?", options: ["Was", "Has she been", "Had she been", "Did she"], answer: 2 },
  { q: "The ground was wet because it ___ raining.", options: ["has been", "was", "had been", "did"], answer: 2 },
  { q: "He ___ sleeping — that's why he was so tired.", options: ["had been", "hadn't been", "was", "has been"], answer: 1 },
  { q: "I ___ waiting for two hours when the bus came.", options: ["was", "had been", "have been", "did"], answer: 1 },
  { q: "___ they arguing before you arrived?", options: ["Were", "Had they been", "Have they been", "Did they"], answer: 1 },
  { q: "She looked tired because she ___ working all day.", options: ["has been", "was", "had been", "did"], answer: 2 },
  { q: "He had been waiting ___ three hours.", options: ["since", "during", "for", "while"], answer: 2 },
  { q: "She had been studying ___ Monday.", options: ["for", "during", "while", "since"], answer: 3 },
  { q: "Had she been studying? — Yes, she ___.", options: ["did", "was", "had", "has"], answer: 2 },
  { q: "By the time they finished, they ___ working for six hours.", options: ["have been", "were", "had been", "did"], answer: 2 },
  { q: "She ___ eating properly, so she felt weak.", options: ["had been", "hadn't been", "wasn't", "didn't"], answer: 1 },
  { q: "His eyes were red because he ___ crying.", options: ["has been", "was", "had been", "did"], answer: 2 },
  { q: "They ___ living there ___ years before moving.", options: ["had been / for", "were / since", "have been / for", "did / since"], answer: 0 },
  { q: "He was exhausted because he ___ sleeping well.", options: ["had been", "hadn't been", "was", "has been"], answer: 1 },
  { q: "___ you waiting long when the taxi arrived?", options: ["Were", "Did", "Had you been", "Have you been"], answer: 2 },
  { q: "She had been working at the hospital ___ the pandemic began.", options: ["for", "during", "while", "since"], answer: 3 },
  { q: "The team was tired because they ___ training hard.", options: ["have been", "were", "had been", "did"], answer: 2 },
];

export const PASTPERFCONT_PDF_CONFIG: LessonPDFConfig = {
  title: "Past Perfect Continuous",
  subtitle: "Duration before a past moment — 4 exercises + answer key",
  level: "C1",
  keyRule: "Subject + had been + verb-ing  →  She had been waiting for an hour when he arrived.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Complete with the Past Perfect Continuous affirmative (had been + verb-ing).",
      hint: "had been + verb-ing",
      questions: [
        "She ___ (wait) for an hour when he finally arrived.",
        "They ___ (run) for 20 minutes when it started to rain.",
        "He ___ (study) all night, so he was exhausted.",
        "By the time we left, I ___ (work) there for five years.",
        "The children ___ (play) all afternoon when their parents got home.",
        "She ___ (cry) — her eyes were red.",
        "By noon, we ___ (drive) for three hours.",
        "He ___ (live) in Paris before he moved to London.",
        "I ___ (read) for an hour when the lights went out.",
        "They ___ (argue) before the manager arrived.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Complete with the Past Perfect Continuous negative (hadn't been + verb-ing).",
      questions: [
        "He ___ (sleep) well — that's why he was so tired.",
        "She ___ (eat) properly, so she felt weak.",
        "They ___ (speak) for months before the reunion.",
        "I ___ (pay) attention, so I missed the point.",
        "He ___ (exercise) regularly, which explained the weight gain.",
        "We ___ (work) long — only 20 minutes when the power cut out.",
        "She ___ (feel) well all week before she collapsed.",
        "The team ___ (train) hard enough, and it showed.",
        "He ___ (study) at all before the exam.",
        "They ___ (communicate) properly, which caused the misunderstanding.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write Past Perfect Continuous questions (Had + subject + been + verb-ing?).",
      questions: [
        "___ she waiting long? (wait)",
        "___ they arguing before you arrived? (argue)",
        "___ he studying all night? (study)",
        "___ you working there for long? (work)",
        "___ the children sleeping? (sleep)",
        "___ she crying before you came? (cry)",
        "___ they living together? (live)",
        "___ he running when he collapsed? (run)",
        "___ she practising before the concert? (practise)",
        "___ they travelling for long? (travel)",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Past Perfect or Past Perfect Continuous? Choose the correct form.",
      questions: [
        "By the time she arrived, I ___ three chapters. (read – completed number)",
        "She looked exhausted because she ___ for hours. (run – duration)",
        "He was proud because he ___ the project. (finish – completed result)",
        "Her hands were covered in paint because she ___ all day. (paint – duration)",
        "I was relieved because I ___ the deadline. (meet – completed result)",
        "She was out of breath because she ___. (run – visible effect)",
        "By noon, he ___ four meetings. (attend – completed number)",
        "His voice was hoarse because he ___ all evening. (sing – duration)",
        "When I arrived, she ___ all the food. (eat – completion)",
        "The road was flooded because it ___ for hours. (rain – duration)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — Past Perfect Continuous affirmative",
      answers: ["had been waiting", "had been running", "had been studying", "had been working", "had been playing", "had been crying", "had been driving", "had been living", "had been reading", "had been arguing"],
    },
    {
      exercise: 2,
      subtitle: "Medium — Past Perfect Continuous negative",
      answers: ["hadn't been sleeping", "hadn't been eating", "hadn't been speaking", "hadn't been paying", "hadn't been exercising", "hadn't been working", "hadn't been feeling", "hadn't been training", "hadn't been studying", "hadn't been communicating"],
    },
    {
      exercise: 3,
      subtitle: "Medium — Past Perfect Continuous questions",
      answers: [
        "Had she been waiting long?",
        "Had they been arguing before you arrived?",
        "Had he been studying all night?",
        "Had you been working there for long?",
        "Had the children been sleeping?",
        "Had she been crying before you came?",
        "Had they been living together?",
        "Had he been running when he collapsed?",
        "Had she been practising before the concert?",
        "Had they been travelling for long?",
      ],
    },
    {
      exercise: 4,
      subtitle: "Hard — Past Perfect vs Past Perfect Continuous",
      answers: ["had read", "had been running", "had finished", "had been painting", "had met", "had been running", "had attended", "had been singing", "had eaten", "had been raining"],
    },
  ],
};
