import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const FUTCONT_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "At 8 PM, I ___ watching the match.", options: ["will be", "won't be", "am going to", "will"], answer: 0 },
  { q: "She ___ working this weekend — she's on holiday.", options: ["will be", "won't be", "isn't", "doesn't"], answer: 1 },
  { q: "___ you be working late tonight?", options: ["Are", "Do", "Will", "Shall"], answer: 2 },
  { q: "This time next week, we ___ sitting on the beach.", options: ["won't be", "will be", "sit", "will"], answer: 1 },
  { q: "Future Continuous = will be + ___", options: ["base verb", "past participle", "verb-ing", "to + verb"], answer: 2 },
  { q: "When you call, they ___ having dinner.", options: ["are", "will be", "will have", "won't be"], answer: 1 },
  { q: "\"Will they be coming?\" — \"Yes, ___.\"", options: ["they are", "they will", "they do", "they will be coming"], answer: 1 },
  { q: "\"Will you be using the car?\" — \"No, ___.\"", options: ["I don't", "I won't", "I'm not", "I haven't"], answer: 1 },
  { q: "Don't call at 3 PM — I ___ running.", options: ["will", "will be", "won't be", "am going to"], answer: 1 },
  { q: "He ___ joining us for lunch — he has a meeting.", options: ["will be", "won't be", "isn't", "doesn't"], answer: 1 },
  { q: "At this time tomorrow, the children ___ playing in the park.", options: ["won't be", "will be", "play", "are"], answer: 1 },
  { q: "___ she be travelling on Friday?", options: ["Does", "Is", "Will", "Has"], answer: 2 },
  { q: "Will he be ___ by the time we arrive?", options: ["sleep", "slept", "sleeping", "sleeps"], answer: 2 },
  { q: "I ___ sleeping when you get back — I have a deadline.", options: ["will be", "won't be", "am not", "don't"], answer: 1 },
  { q: "By midnight, the team ___ still working.", options: ["won't be", "will be", "works", "will"], answer: 1 },
  { q: "Will you be using your car? — polite question to avoid ___.", options: ["confusing", "imposing", "asking", "helping"], answer: 1 },
  { q: "sit → ___ (Future Continuous -ing form)", options: ["siting", "siteing", "sitting", "sitten"], answer: 2 },
  { q: "make → ___ (Future Continuous -ing form)", options: ["makeing", "making", "maked", "makes"], answer: 1 },
  { q: "She ___ making breakfast when you wake up.", options: ["will", "will be", "won't", "is going to"], answer: 1 },
  { q: "\"Will he be joining us?\" — \"Yes, ___.\"", options: ["he does", "he is", "he will", "he will be joining"], answer: 2 },
];

export const FUTCONT_PDF_CONFIG: LessonPDFConfig = {
  title: "Future Continuous",
  subtitle: "Actions in progress at a future moment — 4 exercises + answer key",
  level: "B2",
  keyRule: "Subject + will be + verb-ing  →  At 8pm I will be cooking dinner.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the affirmative Future Continuous form (will be + verb-ing).",
      hint: "will be + verb-ing",
      questions: [
        "At 8 PM tonight, I ___ (watch) the match.",
        "This time next week, she ___ (sit) on the beach.",
        "When you call, they ___ (have) dinner.",
        "By noon tomorrow, he ___ (drive) to the airport.",
        "At this time next year, we ___ (study) at university.",
        "The children ___ (sleep) by the time we arrive home.",
        "Don't call at 3 PM — I ___ (run) in the park.",
        "At midnight the team ___ (work) on the deadline.",
        "Tomorrow at dawn, the birds ___ (sing) in the garden.",
        "She ___ (make) breakfast when you wake up.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Easy",
      instruction: "Write the negative Future Continuous form (won't be + verb-ing).",
      hint: "won't be + verb-ing",
      questions: [
        "She ___ (work) this weekend — she's on holiday.",
        "I ___ (join) you tonight — I have a deadline.",
        "They ___ (travel) by train — they're flying.",
        "He ___ (use) the car tomorrow — I can take it.",
        "We ___ (sleep) at midnight — we'll be celebrating!",
        "Don't worry — it ___ (rain) tomorrow.",
        "She ___ (come) to the meeting — she's called in sick.",
        "At noon the office ___ (operate) — it's a public holiday.",
        "I ___ (sit) around doing nothing — I have plans.",
        "The kids ___ (make) noise at bedtime — they'll be exhausted.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write the Future Continuous question (Will + subject + be + verb-ing?).",
      hint: "Will + subject + be + verb-ing?",
      questions: [
        "___ you be working late tonight? (work)",
        "___ she be giving the presentation tomorrow? (give)",
        "___ they be coming to the party? (come)",
        "___ he be waiting for us at the station? (wait)",
        "___ we be travelling at that time? (travel)",
        "\"Will they be coming?\" — \"Yes, ___\"",
        "\"Will you be using the car?\" — \"No, ___\"",
        "\"Will he be joining us?\" — \"Yes, ___\"",
        "\"Will she be working?\" — \"No, ___\"",
        "\"Will they be waiting?\" — \"Yes, ___\"",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Mixed Future Continuous — affirmative, negative, or question. Choose the correct form.",
      questions: [
        "This time tomorrow, I ___ (fly) over the Atlantic.",
        "She ___ (not / work) tonight — she has the evening off.",
        "___ (he / wait) for us at the station?",
        "Don't call at noon — I ___ (drive) to the airport.",
        "By midnight, the team ___ (not / sleep) — they'll be working.",
        "At 10 PM, she ___ (still / work) on her essay.",
        "___ (they / travel) at that time next week?",
        "We ___ (not / join) you tonight — we have other plans.",
        "The children ___ (play) when we arrive.",
        "\"Will you be working late?\" — \"Yes, ___\"",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — will be + verb-ing",
      answers: ["will be watching", "will be sitting", "will be having", "will be driving", "will be studying", "will be sleeping", "will be running", "will be working", "will be singing", "will be making"],
    },
    {
      exercise: 2,
      subtitle: "Easy — won't be + verb-ing",
      answers: ["won't be working", "won't be joining", "won't be travelling", "won't be using", "won't be sleeping", "won't be raining", "won't be coming", "won't be operating", "won't be sitting", "won't be making"],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions and short answers",
      answers: ["Will you be working late tonight?", "Will she be giving the presentation?", "Will they be coming to the party?", "Will he be waiting for us?", "Will we be travelling at that time?", "Yes, they will.", "No, I won't.", "Yes, he will.", "No, she won't.", "Yes, they will."],
    },
    {
      exercise: 4,
      subtitle: "Hard — mixed Future Continuous",
      answers: ["will be flying", "won't be working", "Will he be waiting for us?", "will be driving", "won't be sleeping", "will still be working", "Will they be travelling?", "won't be joining", "will be playing", "Yes, I will."],
    },
  ],
};
