import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PPC_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "I ___ been studying for three hours.", options: ["have", "has", "had", "am"], answer: 0 },
  { q: "She ___ been working here since 2020.", options: ["have", "has", "had", "is"], answer: 1 },
  { q: "They ___ been waiting for over an hour.", options: ["have", "has", "had", "are"], answer: 0 },
  { q: "He ___ been playing the guitar since he was a child.", options: ["have", "has", "had", "is"], answer: 1 },
  { q: "We ___ been learning French for two years.", options: ["have", "has", "had", "are"], answer: 0 },
  { q: "___ she been crying? Her eyes are red.", options: ["Have", "Has", "Had", "Is"], answer: 1 },
  { q: "I have been ___ for a long time.", options: ["wait", "waits", "waited", "waiting"], answer: 3 },
  { q: "She ___ been running — look, she's out of breath.", options: ["have", "has", "had", "is"], answer: 1 },
  { q: "___ you been sleeping enough lately?", options: ["Have", "Has", "Had", "Are"], answer: 0 },
  { q: "He hasn't been ___ much recently.", options: ["exercise", "exercises", "exercised", "exercising"], answer: 3 },
  { q: "They ___ been talking for hours.", options: ["have", "has", "had", "are"], answer: 0 },
  { q: "How long ___ she been learning Spanish?", options: ["have", "has", "had", "is"], answer: 1 },
  { q: "I've been ___ this book all week.", options: ["read", "reads", "read", "reading"], answer: 3 },
  { q: "She has been working ___ 8 am.", options: ["for", "since", "ago", "during"], answer: 1 },
  { q: "We have been living here ___ five years.", options: ["since", "for", "ago", "until"], answer: 1 },
  { q: "___ they been arguing again?", options: ["Have", "Has", "Had", "Are"], answer: 0 },
  { q: "He ___ been feeling well lately.", options: ["haven't", "hasn't", "hadn't", "isn't"], answer: 1 },
  { q: "\"Has she been working here long?\" — \"Yes, ___.\"", options: ["she has", "she does", "she is", "she had"], answer: 0 },
  { q: "The children ___ been playing outside all afternoon.", options: ["have", "has", "had", "are"], answer: 0 },
  { q: "It ___ been raining for three days now.", options: ["have", "has", "had", "is"], answer: 1 },
];

export const PPC_PDF_CONFIG: LessonPDFConfig = {
  title: "Present Perfect Continuous",
  subtitle: "Ongoing actions with duration — 4 exercises + answer key",
  level: "B2",
  keyRule: "Subject + have/has been + verb-ing  →  I have been studying for 3 hours. / She has been working here since 2020.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Complete with have been or has been + the -ing form of the verb in brackets.",
      hint: "have been (I/you/we/they) · has been (he/she/it)",
      questions: [
        "She ___ (work) here since January.",
        "I ___ (study) for three hours.",
        "They ___ (wait) for a long time.",
        "He ___ (play) football since he was six.",
        "We ___ (learn) Spanish for two years.",
        "It ___ (rain) all morning.",
        "She ___ (run) — look at her face!",
        "He ___ (read) that book for weeks.",
        "They ___ (travel) around Europe.",
        "I ___ (think) about your offer.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the negative form: haven't been / hasn't been + verb-ing.",
      questions: [
        "She ___ (sleep) well lately.",
        "I ___ (exercise) enough recently.",
        "They ___ (communicate) well.",
        "He ___ (eat) properly since he started the new job.",
        "We ___ (see) each other for months.",
        "It ___ (work) properly all week.",
        "She ___ (practise) her presentation enough.",
        "They ___ (pay) attention in class.",
        "He ___ (feel) well for a few days.",
        "I ___ (make) much progress recently.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write questions: Have/Has + subject + been + verb-ing?",
      questions: [
        "___ she ___ (work) here long?",
        "___ you ___ (sleep) enough?",
        "___ they ___ (wait) long?",
        "___ he ___ (exercise) regularly?",
        "___ it ___ (rain) all day?",
        "___ she ___ (cry)?",
        "___ we ___ (make) progress?",
        "How long ___ you ___ (study) English?",
        "How long ___ she ___ (live) here?",
        "What ___ they ___ (do) all day?",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Present Perfect or Present Perfect Continuous? Write the correct form.",
      questions: [
        "I ___ (read) three books this month. (focus: how many — completion)",
        "I ___ (read) for two hours. (focus: how long — duration)",
        "She ___ (write) five emails already. (focus: completed tasks)",
        "She ___ (write) emails all morning. (focus: ongoing activity)",
        "He ___ (live) in Paris. He knows it very well. (result)",
        "He ___ (live) in Paris since 2019. (duration)",
        "They ___ (finish) the project. (result: it's done)",
        "They ___ (work) on the project for months. (duration)",
        "I ___ (lose) my keys. I can't find them. (result)",
        "I ___ (look) for my keys for an hour. (ongoing process)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — have been / has been + verb-ing",
      answers: [
        "has been working", "have been studying", "have been waiting", "has been playing",
        "have been learning", "has been raining", "has been running", "has been reading",
        "have been travelling", "have been thinking",
      ],
    },
    {
      exercise: 2,
      subtitle: "Medium — negative PPC",
      answers: [
        "hasn't been sleeping", "haven't been exercising", "haven't been communicating",
        "hasn't been eating", "haven't been seeing", "hasn't been working",
        "hasn't been practising", "haven't been paying", "hasn't been feeling", "haven't been making",
      ],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions",
      answers: [
        "Has she been working here long?", "Have you been sleeping enough?", "Have they been waiting long?",
        "Has he been exercising regularly?", "Has it been raining all day?", "Has she been crying?",
        "Have we been making progress?", "How long have you been studying English?",
        "How long has she been living here?", "What have they been doing all day?",
      ],
    },
    {
      exercise: 4,
      subtitle: "Hard — PP vs PPC",
      answers: [
        "have read", "have been reading", "has written", "has been writing",
        "has lived", "has been living", "have finished", "have been working",
        "have lost", "have been looking",
      ],
    },
  ],
};
