import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const FUTSIM_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "I ___ call you later, I promise.", options: ["will call", "am calling", "calls", "called"], answer: 0 },
  { q: "She ___ be at the party — she's busy.", options: ["will", "won't", "isn't going", "doesn't"], answer: 1 },
  { q: "___ you help me with this?", options: ["Do", "Are", "Will", "Have"], answer: 2 },
  { q: "They ___ finish the project by Friday.", options: ["are finishing", "will finish", "finish", "finishes"], answer: 1 },
  { q: "I think it ___ rain tomorrow.", options: ["rains", "is raining", "will rain", "rained"], answer: 2 },
  { q: "He ___ probably be late again.", options: ["will", "is", "does", "won't"], answer: 0 },
  { q: "\"Will you be there?\" — \"Yes, ___.\"", options: ["I do", "I am", "I will", "I can"], answer: 2 },
  { q: "\"Will she pass?\" — \"No, ___.\"", options: ["she doesn't", "she won't", "she isn't", "she can't"], answer: 1 },
  { q: "I ___ (not) tell anyone your secret.", options: ["won't", "don't", "will not going to", "am not"], answer: 0 },
  { q: "After will / won't, always use the ___ form.", options: ["past", "-ing", "base", "-s"], answer: 2 },
  { q: "She will ___ the answer soon.", options: ["knows", "knowing", "known", "know"], answer: 3 },
  { q: "It ___ snow in the desert.", options: ["will", "won't", "doesn't going to", "isn't will"], answer: 1 },
  { q: "I'll ___ that for you. (offer)", options: ["carry", "carrying", "carries", "carried"], answer: 0 },
  { q: "Technology ___ change a lot in the future.", options: ["is changing", "changes", "will change", "changed"], answer: 2 },
  { q: "___ he call back later?", options: ["Does", "Is", "Will", "Has"], answer: 2 },
  { q: "I'm sure they ___ love the surprise.", options: ["will", "are", "do", "won't"], answer: 0 },
  { q: "The contraction of 'will not' is ___.", options: ["willn't", "won't", "wouldn't", "wil'nt"], answer: 1 },
  { q: "We ___ be home before midnight.", options: ["will", "won't", "are not going", "doesn't"], answer: 1 },
  { q: "I think she ___ get the job.", options: ["is getting", "gets", "will get", "got"], answer: 2 },
  { q: "Spontaneous decisions use ___, not 'going to'.", options: ["will", "won't", "would", "shall"], answer: 0 },
];

export const FUTSIM_PDF_CONFIG: LessonPDFConfig = {
  title: "Future Simple (will)",
  subtitle: "Predictions, promises & spontaneous decisions — 4 exercises + answer key",
  level: "A2",
  keyRule: "Subject + will + base verb  →  She will help you. / I won't be late.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the correct affirmative Future Simple form (will + base verb).",
      hint: "will + base form",
      questions: [
        "She ___ (call) you later.",
        "I ___ (help) you with that.",
        "They ___ (arrive) tomorrow morning.",
        "He ___ (probably / be) late again.",
        "We ___ (finish) the project by Friday.",
        "I think it ___ (be) a great concert.",
        "Technology ___ (change) a lot in the future.",
        "She ___ (turn) 30 next year.",
        "The sun ___ (rise) at 6 AM tomorrow.",
        "I ___ (carry) that bag for you.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Easy",
      instruction: "Write the correct negative Future Simple form (won't + base verb).",
      hint: "won't + base form",
      questions: [
        "I ___ (tell) anyone about this.",
        "She ___ (be) at the party — she has other plans.",
        "It ___ (snow) in the desert.",
        "They ___ (forget) your help.",
        "I ___ (give up) easily.",
        "He ___ (accept) their offer.",
        "We ___ (be) home before midnight.",
        "The weather ___ (improve) this week.",
        "I ___ (let) you down, I promise.",
        "She ___ (mind) waiting for a few minutes.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write the Future Simple question using 'Will + subject + base verb?'.",
      hint: "Will + subject + base verb?",
      questions: [
        "___ you help me with this? (help)",
        "___ she come to the meeting? (come)",
        "___ they arrive on time? (arrive)",
        "___ it rain tomorrow? (rain)",
        "___ he call back? (call)",
        "\"Will you be there?\" — \"Yes, ___\"",
        "\"Will she pass?\" — \"No, ___\"",
        "\"Will it rain?\" — \"Yes, ___\"",
        "\"Will they come?\" — \"No, ___\"",
        "\"Will he be there?\" — \"Yes, ___\"",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Mixed Future Simple — affirmative, negative, or question. Choose the correct form.",
      questions: [
        "Don't worry — I ___ (help) you.",
        "I ___ (not / tell) anyone your secret.",
        "___ (you / be) home for dinner?",
        "She ___ (probably / pass) the exam — she studied hard.",
        "He ___ (not / accept) that offer.",
        "I ___ (have) the soup, please.",
        "___ (she / be) at the office tomorrow?",
        "\"Will you call me?\" — \"Yes, ___\"",
        "They ___ (not / be) ready on time.",
        "I think everything ___ (be) fine.",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — affirmative will + base verb",
      answers: ["will call", "will help", "will arrive", "will probably be", "will finish", "will be", "will change", "will turn", "will rise", "will carry"],
    },
    {
      exercise: 2,
      subtitle: "Easy — negative won't + base verb",
      answers: ["won't tell", "won't be", "won't snow", "won't forget", "won't give up", "won't accept", "won't be", "won't improve", "won't let", "won't mind"],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions and short answers",
      answers: ["Will you help me?", "Will she come?", "Will they arrive?", "Will it rain?", "Will he call back?", "Yes, I will.", "No, she won't.", "Yes, it will.", "No, they won't.", "Yes, he will."],
    },
    {
      exercise: 4,
      subtitle: "Hard — mixed Future Simple",
      answers: ["will help", "won't tell", "Will you be home for dinner?", "will probably pass", "won't accept", "will have", "Will she be at the office tomorrow?", "Yes, I will.", "won't be", "will be"],
    },
  ],
};
