import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PASTPERF_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "She ___ already left when I arrived.", options: ["has", "had", "have", "did"], answer: 1 },
  { q: "By the time he called, I ___ eaten dinner.", options: ["have", "was", "had", "did"], answer: 2 },
  { q: "They ___ finished before the deadline.", options: ["have", "did", "were", "had"], answer: 3 },
  { q: "He ___ never seen anything like it before.", options: ["didn't", "have", "were", "had"], answer: 3 },
  { q: "After she ___ read the letter, she smiled.", options: ["has", "was", "had", "did"], answer: 2 },
  { q: "___ they finished by the time you arrived?", options: ["Have", "Did", "Had", "Were"], answer: 2 },
  { q: "I ___ just packed when the taxi came.", options: ["have", "did", "was", "had"], answer: 3 },
  { q: "She ___ never been to Japan before that trip.", options: ["didn't", "hasn't", "hadn't", "wasn't"], answer: 2 },
  { q: "Had you met him before? — Yes, I ___.", options: ["did", "had", "was", "have"], answer: 1 },
  { q: "He realised he ___ brought his wallet.", options: ["didn't", "hasn't", "hadn't", "wasn't"], answer: 2 },
  { q: "We ___ lived there for three years before moving.", options: ["have", "had", "has", "did"], answer: 1 },
  { q: "By 2010, she ___ written two novels.", options: ["has", "was", "had", "did"], answer: 2 },
  { q: "I told him I ___ seen that film yet.", options: ["haven't", "hadn't", "didn't", "wasn't"], answer: 1 },
  { q: "Before she became famous, she ___ worked in a café.", options: ["has", "have", "had", "did"], answer: 2 },
  { q: "When I got there, the match ___ already ended.", options: ["has", "have", "had", "was"], answer: 2 },
  { q: "Had they eaten before the party? — No, they ___.", options: ["didn't", "hadn't", "haven't", "weren't"], answer: 1 },
  { q: "She was sad because she ___ lost her ring.", options: ["has", "have", "had", "did"], answer: 2 },
  { q: "He said he ___ the report.", options: ["sent", "has sent", "had sent", "was sending"], answer: 2 },
  { q: "They ___ spoken for years before the reunion.", options: ["didn't", "haven't", "weren't", "hadn't"], answer: 3 },
  { q: "If I ___ known, I would have helped.", options: ["have", "had", "has", "did"], answer: 1 },
];

export const PASTPERF_PDF_CONFIG: LessonPDFConfig = {
  title: "Past Perfect",
  subtitle: "Action before another past action — 4 exercises + answer key",
  level: "B2",
  keyRule: "Subject + had + past participle  →  She had finished before he arrived.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Complete with the Past Perfect affirmative (had + past participle).",
      hint: "had + past participle",
      questions: [
        "She ___ (leave) before he arrived.",
        "They ___ (finish) the exam by noon.",
        "By the time we got there, the film ___ (start).",
        "He ___ (eat) dinner before the guests came.",
        "I ___ (see) that film three times before last night.",
        "She told me she ___ (meet) him before.",
        "By 2015, he ___ (live) in five countries.",
        "After she ___ (read) the letter, she smiled.",
        "They ___ (already / decide) when I called.",
        "We ___ (never / visit) Paris before that trip.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Complete with the Past Perfect negative (hadn't + past participle).",
      questions: [
        "He ___ (see) her before that day.",
        "They ___ (meet) each other before the conference.",
        "She ___ (eat) anything since breakfast, so she was starving.",
        "I ___ (hear) that song before, but I loved it immediately.",
        "We ___ (finish) the report when the boss asked for it.",
        "He realised he ___ (bring) his wallet.",
        "By the time the film started, they ___ (arrive) yet.",
        "She ___ (study) English before she moved to London.",
        "I told him I ___ (see) that film yet.",
        "They ___ (speak) for years before the reunion.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write Past Perfect questions using Had + subject + past participle.",
      questions: [
        "___ they finished before you arrived? (finish)",
        "___ she ever been to Japan before that trip? (be)",
        "___ the train already left when you arrived? (leave)",
        "___ he finished his homework before dinner? (finish)",
        "___ you ever tried sushi before last night? (try)",
        "___ the meeting started by the time you arrived? (start)",
        "___ they read the instructions? (read)",
        "___ she lived there before? (live)",
        "___ we met before? (meet)",
        "___ he left a message before he hung up? (leave)",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Past Perfect or Past Simple? Choose the correct tense.",
      questions: [
        "When I arrived, most people ___ already gone home. (go)",
        "She ___ the door and walked outside. (open)",
        "By the time the ambulance arrived, the patient ___ unconscious. (become)",
        "After we ___ all the food, we felt sick. (eat)",
        "He ___ his keys, so he couldn't get in. (lose)",
        "They ___ the film before, so they didn't watch it. (see)",
        "She ___ the room as soon as she heard the news. (leave)",
        "Before she became famous, she ___ in a small café. (work)",
        "He said he ___ the report, but it wasn't there. (send)",
        "I was relieved when I realised I ___ my passport. (not / lose)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — Past Perfect affirmative",
      answers: ["had left", "had finished", "had started", "had eaten", "had seen", "had met", "had lived", "had read", "had already decided", "had never visited"],
    },
    {
      exercise: 2,
      subtitle: "Medium — Past Perfect negative",
      answers: ["hadn't seen", "hadn't met", "hadn't eaten", "hadn't heard", "hadn't finished", "hadn't brought", "hadn't arrived", "hadn't studied", "hadn't seen", "hadn't spoken"],
    },
    {
      exercise: 3,
      subtitle: "Medium — Past Perfect questions",
      answers: [
        "Had they finished before you arrived?",
        "Had she ever been to Japan before that trip?",
        "Had the train already left when you arrived?",
        "Had he finished his homework before dinner?",
        "Had you ever tried sushi before last night?",
        "Had the meeting started by the time you arrived?",
        "Had they read the instructions?",
        "Had she lived there before?",
        "Had we met before?",
        "Had he left a message before he hung up?",
      ],
    },
    {
      exercise: 4,
      subtitle: "Hard — Past Perfect vs Past Simple",
      answers: ["had gone", "opened", "had become", "had eaten", "had lost", "had seen", "left", "had worked", "had sent", "hadn't lost"],
    },
  ],
};
