import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PS_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "She ___ to the shops yesterday.", options: ["go", "goes", "went", "gone"], answer: 2 },
  { q: "They ___ tennis last Sunday.", options: ["play", "plays", "played", "playing"], answer: 2 },
  { q: "He ___ (not) finish his homework.", options: ["didn't finished", "didn't finish", "doesn't finish", "not finish"], answer: 1 },
  { q: "I ___ a great film last night.", options: ["seed", "saw", "see", "seen"], answer: 1 },
  { q: "___ she call you back?", options: ["Was", "Is", "Did", "Does"], answer: 2 },
  { q: "We ___ in Paris for two years.", options: ["live", "lived", "liveed", "were living"], answer: 1 },
  { q: "He ___ (stop) the car at the lights.", options: ["stoped", "stopping", "stopped", "stops"], answer: 2 },
  { q: "She ___ (study) all evening.", options: ["studyed", "studied", "studied", "studying"], answer: 2 },
  { q: "\"Did you enjoy the trip?\" — \"Yes, ___.\"", options: ["I enjoyed", "I did", "I was", "I do"], answer: 1 },
  { q: "They ___ (not/come) to the party.", options: ["didn't came", "didn't come", "don't come", "weren't come"], answer: 1 },
  { q: "What ___ you do at the weekend?", options: ["were", "have", "did", "was"], answer: 2 },
  { q: "She ___ (write) an email to her boss.", options: ["writed", "writing", "wrote", "write"], answer: 2 },
  { q: "He ___ (take) the train to the city.", options: ["taked", "took", "takes", "taking"], answer: 1 },
  { q: "\"Did she win?\" — \"No, ___.\"", options: ["she didn't", "she wasn't", "she not", "she doesn't"], answer: 0 },
  { q: "They ___ (eat) at a nice restaurant.", options: ["eated", "eaten", "eat", "ate"], answer: 3 },
  { q: "She ___ (like) the new restaurant.", options: ["likeed", "liked", "like", "liking"], answer: 1 },
  { q: "___ he find his wallet?", options: ["Was", "Is", "Did", "Does"], answer: 2 },
  { q: "He ___ (not/tell) anyone about it.", options: ["didn't told", "didn't tell", "don't tell", "not tell"], answer: 1 },
  { q: "I ___ (feel) really tired after the walk.", options: ["feeled", "felled", "felt", "feel"], answer: 2 },
  { q: "She ___ (close) the window before leaving.", options: ["closeed", "closed", "close", "closing"], answer: 1 },
];

export const PS_PDF_CONFIG: LessonPDFConfig = {
  title: "Past Simple",
  subtitle: "Completed past actions — 4 exercises + answer key",
  level: "A2",
  keyRule: "Subject + verb-ed / irregular form  →  She worked. / He went.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the correct Past Simple form of the regular verb.",
      hint: "verb-ed",
      questions: [
        "She ___ hard for the exam. (work / worked)",
        "They ___ tennis yesterday. (play / played)",
        "He ___ the car at the lights. (stop / stopped)",
        "She ___ the window before bed. (close / closed)",
        "I ___ to call you all morning. (try / tried)",
        "They ___ the football match. (watch / watched)",
        "He ___ the trip carefully. (plan / planned)",
        "She ___ at the party. (dance / danced)",
        "We ___ the museum last Sunday. (visit / visited)",
        "I ___ for three hours. (study / studied)",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the correct irregular Past Simple form.",
      hint: "irregular",
      questions: [
        "She ___ to the gym. (go → went)",
        "He ___ a great time. (have → had)",
        "I ___ an old friend. (see → saw)",
        "They ___ at a nice café. (eat → ate)",
        "She ___ an email. (write → wrote)",
        "He ___ the train. (take → took)",
        "We ___ a pizza. (make → made)",
        "She ___ about the problem. (think → thought)",
        "He ___ a new laptop. (buy → bought)",
        "They ___ home very late. (come → came)",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write the negative form using didn't + base form.",
      hint: "didn't + verb",
      questions: [
        "I ___ breakfast this morning. (not/eat)",
        "She ___ to school yesterday. (not/go)",
        "He ___ his homework on time. (not/finish)",
        "They ___ to the meeting. (not/come)",
        "We ___ about the change. (not/know)",
        "She ___ well last night. (not/sleep)",
        "He ___ anyone about it. (not/tell)",
        "I ___ what to say. (not/know)",
        "We ___ the match. (not/win)",
        "She ___ to leave early. (not/want)",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Write the correct Past Simple form — affirmative, negative, or question.",
      hint: "all forms",
      questions: [
        "She ___ him a lovely present. (give)",
        "___ he find his wallet? (find)",
        "They ___ the project before the deadline. (finish)",
        "I ___ really tired after the walk. (feel)",
        "She ___ well last night. (not/sleep)",
        "We ___ a week in Paris. (spend)",
        "He ___ his phone on the way home. (drop)",
        "___ they enjoy the concert? (enjoy)",
        "She ___ to leave the party early. (not/want)",
        "What ___ you do at the weekend? (do)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — regular verbs",
      answers: ["worked", "played", "stopped", "closed", "tried", "watched", "planned", "danced", "visited", "studied"],
    },
    {
      exercise: 2,
      subtitle: "Medium — irregular verbs",
      answers: ["went", "had", "saw", "ate", "wrote", "took", "made", "thought", "bought", "came"],
    },
    {
      exercise: 3,
      subtitle: "Medium — negatives with didn't",
      answers: ["didn't eat", "didn't go", "didn't finish", "didn't come", "didn't know", "didn't sleep", "didn't tell", "didn't know", "didn't win", "didn't want"],
    },
    {
      exercise: 4,
      subtitle: "Hard — mixed forms",
      answers: ["gave", "Did he find his wallet?", "finished", "felt", "didn't sleep", "spent", "dropped", "Did they enjoy the concert?", "didn't want", "What did you do at the weekend?"],
    },
  ],
};
