import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PASTCONT_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "She ___ a book at 9 PM last night.", options: ["read", "was reading", "were reading", "reads"], answer: 1 },
  { q: "I ___ cooking when you called.", options: ["am", "was", "were", "is"], answer: 1 },
  { q: "They ___ football all afternoon.", options: ["was playing", "were played", "were playing", "are playing"], answer: 2 },
  { q: "He ___ working from home yesterday.", options: ["were", "be", "am", "was"], answer: 3 },
  { q: "We ___ watching a film at that time.", options: ["was", "be", "were", "is"], answer: 2 },
  { q: "___ she sleeping when you arrived?", options: ["Did", "Am", "Was", "Were"], answer: 2 },
  { q: "They ___ coming to the party — they cancelled.", options: ["wasn't", "weren't", "didn't", "not"], answer: 1 },
  { q: "I ___ cooking when the phone rang.", options: ["was", "were", "am", "be"], answer: 0 },
  { q: "She ___ (not work) — she was ill.", options: ["didn't work", "wasn't working", "weren't working", "not worked"], answer: 1 },
  { q: "While she ___ reading, he was cooking.", options: ["is", "were", "am", "was"], answer: 3 },
  { q: "___ you listening when I explained?", options: ["Did", "Was", "Were", "Are"], answer: 2 },
  { q: "It ___ raining all night long.", options: ["were", "is", "was", "be"], answer: 2 },
  { q: "\"Were they playing?\" — \"Yes, ___.\"", options: ["they are", "they were", "they did", "they was"], answer: 1 },
  { q: "He ___ paying attention during the lesson.", options: ["wasn't", "weren't", "didn't", "not"], answer: 0 },
  { q: "The children ___ making noise when I arrived.", options: ["was", "is", "were", "be"], answer: 2 },
  { q: "\"Was she coming?\" — \"No, ___.\"", options: ["she wasn't", "she weren't", "she didn't", "she not"], answer: 0 },
  { q: "I ___ walking home ___ I saw the accident.", options: ["was / while", "were / when", "was / when", "am / when"], answer: 2 },
  { q: "run → ___", options: ["runing", "running", "runeing", "runnng"], answer: 1 },
  { q: "make → ___", options: ["makeing", "makking", "making", "maked"], answer: 2 },
  { q: "___ she studying for the exam last night?", options: ["Did", "Was", "Were", "Is"], answer: 1 },
];

export const PASTCONT_PDF_CONFIG: LessonPDFConfig = {
  title: "Past Continuous",
  subtitle: "Actions in progress in the past — 4 exercises + answer key",
  level: "B1",
  keyRule: "Subject + was/were + verb-ing  →  She was reading. / They were playing.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the affirmative Past Continuous form of the verb in brackets.",
      hint: "was/were + -ing",
      questions: [
        "She ___ (read) a book at 9 PM last night.",
        "I ___ (cook) dinner when you called.",
        "They ___ (play) football all afternoon.",
        "He ___ (work) from home yesterday.",
        "We ___ (watch) a film at that time.",
        "The dog ___ (sleep) on the sofa all morning.",
        "It ___ (rain) all night long.",
        "My parents ___ (visit) my aunt this time last week.",
        "She ___ (run) in the park when it started to rain.",
        "The children ___ (make) a lot of noise when I arrived.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the negative Past Continuous form: wasn't / weren't + verb-ing.",
      questions: [
        "She ___ (work) yesterday — she was ill.",
        "I ___ (listen) to you at that moment.",
        "They ___ (come) to the party after all.",
        "He ___ (pay) attention during the lesson.",
        "We ___ (go) out that evening.",
        "It ___ (snow) when we left the house.",
        "You ___ (wear) a coat — weren't you cold?",
        "My phone ___ (charge) when I needed it.",
        "She ___ (talk) to me any more that day.",
        "The kids ___ (do) their homework when I came home.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write a Past Continuous question. Start with Was / Were.",
      questions: [
        "___ she sleeping when you arrived? (sleep)",
        "___ you listening to me at that point? (listen)",
        "___ they coming to the meeting yesterday? (come)",
        "___ he watching TV at 8 PM last night? (watch)",
        "___ I talking too fast during the presentation? (talk)",
        "___ it raining when you left the house? (rain)",
        "\"Was it raining?\" — \"Yes, ___.\"",
        "\"Were you working?\" — \"No, ___.\"",
        "\"Was she coming?\" — \"Yes, ___.\"",
        "\"Were they leaving?\" — \"No, ___.\"",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Choose Past Continuous or Past Simple. Think about background vs. event.",
      questions: [
        "I ___ (cook) when the phone rang.",
        "While she ___ (read), he was cooking dinner.",
        "They ___ (not / wait) for the bus — they walked.",
        "___ (you / sleep) when I called last night?",
        "She ___ (talk) on the phone at midnight.",
        "He ___ (not / watch) TV — he was studying.",
        "While the children ___ (play), the parents were cooking.",
        "It ___ (snow) when we woke up.",
        "We ___ (have) lunch when the fire alarm went off.",
        "I ___ (walk) home when I saw the accident.",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — affirmative was/were + -ing",
      answers: ["was reading", "was cooking", "were playing", "was working", "were watching", "was sleeping", "was raining", "were visiting", "was running", "were making"],
    },
    {
      exercise: 2,
      subtitle: "Medium — negative wasn't/weren't",
      answers: ["wasn't working", "wasn't listening", "weren't coming", "wasn't paying", "weren't going", "wasn't snowing", "weren't wearing", "wasn't charging", "wasn't talking", "weren't doing"],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions Was/Were?",
      answers: ["Was she sleeping?", "Were you listening?", "Were they coming?", "Was he watching?", "Was I talking?", "Was it raining?", "it was", "I wasn't", "she was", "they weren't"],
    },
    {
      exercise: 4,
      subtitle: "Hard — when/while mixed",
      answers: ["was cooking", "was reading", "weren't waiting", "Were you sleeping?", "was talking", "wasn't watching", "were playing", "was snowing", "were having", "was walking"],
    },
  ],
};
