import type { MetadataRoute } from "next";

const BASE = "https://englishnerd.cc";

function u(path: string, priority: number, changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] = "monthly"): MetadataRoute.Sitemap[number] {
  return { url: `${BASE}${path}`, priority, changeFrequency, lastModified: new Date() };
}

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // ── Core ──────────────────────────────────────────────────────────────
    u("/", 1, "weekly"),
    u("/nerd-zone", 0.9, "weekly"),
    u("/grammar", 0.9, "weekly"),
    u("/tenses", 0.9, "weekly"),
    u("/vocabulary", 0.85, "weekly"),
    u("/reading", 0.85, "weekly"),
    u("/listening", 0.85, "weekly"),
    u("/tests", 0.8, "weekly"),
    u("/pro", 0.9, "weekly"),
    u("/about", 0.5, "yearly"),
    u("/contact", 0.4, "yearly"),
    u("/terms", 0.3, "yearly"),
    u("/privacy-policy", 0.3, "yearly"),

    // ── Grammar level hubs ────────────────────────────────────────────────
    u("/grammar/a1", 0.85, "monthly"),
    u("/grammar/a2", 0.85, "monthly"),
    u("/grammar/b1", 0.85, "monthly"),
    u("/grammar/b2", 0.85, "monthly"),
    u("/grammar/c1", 0.85, "monthly"),

    // ── Grammar A1 lessons ────────────────────────────────────────────────
    u("/grammar/a1/adverbs-frequency", 0.75, "monthly"),
    u("/grammar/a1/prepositions-place", 0.75, "monthly"),
    u("/grammar/a1/present-simple-i-you-we-they", 0.75, "monthly"),
    u("/grammar/a1/wh-questions", 0.75, "monthly"),
    u("/grammar/a1/to-be-am-is-are", 0.75, "monthly"),
    u("/grammar/a1/have-has-got", 0.75, "monthly"),
    u("/grammar/a1/plural-nouns", 0.75, "monthly"),
    u("/grammar/a1/present-simple-he-she-it", 0.75, "monthly"),
    u("/grammar/a1/subject-pronouns", 0.75, "monthly"),
    u("/grammar/a1/possessive-adjectives", 0.75, "monthly"),
    u("/grammar/a1/prepositions-time-in-on-at", 0.75, "monthly"),
    u("/grammar/a1/present-simple-negative", 0.75, "monthly"),
    u("/grammar/a1/this-that-these-those", 0.75, "monthly"),
    u("/grammar/a1/much-many-basic", 0.75, "monthly"),
    u("/grammar/a1/some-any", 0.75, "monthly"),
    u("/grammar/a1/present-simple-questions", 0.75, "monthly"),
    u("/grammar/a1/can-cant", 0.75, "monthly"),
    u("/grammar/a1/there-is-there-are", 0.75, "monthly"),
    u("/grammar/a1/countable-uncountable", 0.75, "monthly"),
    u("/grammar/a1/articles-a-an", 0.75, "monthly"),

    // ── Grammar A2 lessons ────────────────────────────────────────────────
    u("/grammar/a2/past-simple-negative-questions", 0.75, "monthly"),
    u("/grammar/a2/superlative-adjectives", 0.75, "monthly"),
    u("/grammar/a2/conjunctions", 0.75, "monthly"),
    u("/grammar/a2/prepositions-movement", 0.75, "monthly"),
    u("/grammar/a2/articles-the", 0.75, "monthly"),
    u("/grammar/a2/possessive-pronouns", 0.75, "monthly"),
    u("/grammar/a2/comparative-adjectives", 0.75, "monthly"),
    u("/grammar/a2/past-simple-irregular", 0.75, "monthly"),
    u("/grammar/a2/time-expressions-past", 0.75, "monthly"),
    u("/grammar/a2/present-continuous", 0.75, "monthly"),
    u("/grammar/a2/verb-ing", 0.75, "monthly"),
    u("/grammar/a2/verb-infinitive", 0.75, "monthly"),
    u("/grammar/a2/past-simple-regular", 0.75, "monthly"),
    u("/grammar/a2/object-pronouns", 0.75, "monthly"),
    u("/grammar/a2/should-shouldnt", 0.75, "monthly"),
    u("/grammar/a2/adverbs-manner", 0.75, "monthly"),
    u("/grammar/a2/have-to", 0.75, "monthly"),
    u("/grammar/a2/present-perfect-intro", 0.75, "monthly"),
    u("/grammar/a2/going-to", 0.75, "monthly"),
    u("/grammar/a2/will-future", 0.75, "monthly"),

    // ── Grammar B1 lessons ────────────────────────────────────────────────
    u("/grammar/b1/modal-possibility", 0.75, "monthly"),
    u("/grammar/b1/past-continuous", 0.75, "monthly"),
    u("/grammar/b1/zero-first-conditional", 0.75, "monthly"),
    u("/grammar/b1/as-as-comparison", 0.75, "monthly"),
    u("/grammar/b1/passive-present", 0.75, "monthly"),
    u("/grammar/b1/wish-past", 0.75, "monthly"),
    u("/grammar/b1/phrasal-verbs", 0.75, "monthly"),
    u("/grammar/b1/reported-statements", 0.75, "monthly"),
    u("/grammar/b1/all-conditionals", 0.75, "monthly"),
    u("/grammar/b1/second-conditional", 0.75, "monthly"),
    u("/grammar/b1/reported-questions", 0.75, "monthly"),
    u("/grammar/b1/modal-deduction", 0.75, "monthly"),
    u("/grammar/b1/past-perfect", 0.75, "monthly"),
    u("/grammar/b1/relative-clauses-non-defining", 0.75, "monthly"),
    u("/grammar/b1/would-past-habits", 0.75, "monthly"),
    u("/grammar/b1/present-perfect-continuous", 0.75, "monthly"),
    u("/grammar/b1/too-enough", 0.75, "monthly"),
    u("/grammar/b1/passive-past", 0.75, "monthly"),
    u("/grammar/b1/so-such", 0.75, "monthly"),
    u("/grammar/b1/used-to", 0.75, "monthly"),
    u("/grammar/b1/relative-clauses-defining", 0.75, "monthly"),

    // ── Grammar B2 lessons ────────────────────────────────────────────────
    u("/grammar/b2/future-perfect", 0.75, "monthly"),
    u("/grammar/b2/participle-clauses", 0.75, "monthly"),
    u("/grammar/b2/future-continuous", 0.75, "monthly"),
    u("/grammar/b2/reported-speech-advanced", 0.75, "monthly"),
    u("/grammar/b2/inversion", 0.75, "monthly"),
    u("/grammar/b2/passive-advanced", 0.75, "monthly"),
    u("/grammar/b2/relative-clauses-advanced", 0.75, "monthly"),
    u("/grammar/b2/quantifiers-advanced", 0.75, "monthly"),
    u("/grammar/b2/wish-would", 0.75, "monthly"),
    u("/grammar/b2/cleft-sentences", 0.75, "monthly"),
    u("/grammar/b2/linking-words", 0.75, "monthly"),
    u("/grammar/b2/mixed-conditionals", 0.75, "monthly"),
    u("/grammar/b2/past-perfect-continuous", 0.75, "monthly"),
    u("/grammar/b2/third-conditional", 0.75, "monthly"),
    u("/grammar/b2/all-conditionals-b2", 0.75, "monthly"),
    u("/grammar/b2/modal-perfect", 0.75, "monthly"),
    u("/grammar/b2/gerunds-infinitives", 0.75, "monthly"),
    u("/grammar/b2/causative", 0.75, "monthly"),

    // ── Grammar C1 lessons ────────────────────────────────────────────────
    u("/grammar/c1/complex-noun-phrases", 0.75, "monthly"),
    u("/grammar/c1/advanced-inversion", 0.75, "monthly"),
    u("/grammar/c1/complex-passives", 0.75, "monthly"),
    u("/grammar/c1/advanced-discourse-markers", 0.75, "monthly"),
    u("/grammar/c1/passive-infinitives", 0.75, "monthly"),
    u("/grammar/c1/word-formation", 0.75, "monthly"),
    u("/grammar/c1/advanced-relative-clauses", 0.75, "monthly"),
    u("/grammar/c1/reported-speech-c1", 0.75, "monthly"),
    u("/grammar/c1/extraposition", 0.75, "monthly"),
    u("/grammar/c1/concession-contrast", 0.75, "monthly"),
    u("/grammar/c1/hedging-language", 0.75, "monthly"),
    u("/grammar/c1/fronting-emphasis", 0.75, "monthly"),
    u("/grammar/c1/nominalisation", 0.75, "monthly"),
    u("/grammar/c1/ellipsis-substitution", 0.75, "monthly"),
    u("/grammar/c1/inverted-conditionals", 0.75, "monthly"),
    u("/grammar/c1/advanced-participle-clauses", 0.75, "monthly"),
    u("/grammar/c1/subjunctive", 0.75, "monthly"),
    u("/grammar/c1/advanced-modals", 0.75, "monthly"),

    // ── Nerd Zone ─────────────────────────────────────────────────────────
    u("/nerd-zone/recommendations", 0.8, "weekly"),
    u("/nerd-zone/slang", 0.75, "weekly"),
    u("/nerd-zone/slang/b1", 0.7, "weekly"),
    u("/nerd-zone/slang/b2", 0.7, "weekly"),
    u("/nerd-zone/slang/c1", 0.7, "weekly"),
    u("/nerd-zone/live-phrases", 0.75, "weekly"),
    u("/nerd-zone/live-phrases/b1", 0.7, "weekly"),
    u("/nerd-zone/live-phrases/b2", 0.7, "weekly"),
    u("/nerd-zone/live-phrases/c1", 0.7, "weekly"),
    u("/nerd-zone/phrasal-verbs", 0.75, "weekly"),
    u("/nerd-zone/phrasal-verbs/b1", 0.7, "weekly"),
    u("/nerd-zone/phrasal-verbs/b2", 0.7, "weekly"),
    u("/nerd-zone/phrasal-verbs/c1", 0.7, "weekly"),
    u("/nerd-zone/irregular-verbs", 0.75, "weekly"),
    u("/nerd-zone/useful-sites", 0.65, "monthly"),
    u("/nerd-zone/recommendations/lion-king", 0.65, "monthly"),
    u("/nerd-zone/recommendations/toy-story", 0.65, "monthly"),
    u("/nerd-zone/recommendations/bluey", 0.65, "monthly"),
    u("/nerd-zone/recommendations/friends", 0.65, "monthly"),
    u("/nerd-zone/recommendations/the-office", 0.65, "monthly"),
    u("/nerd-zone/recommendations/the-simpsons", 0.65, "monthly"),
    u("/nerd-zone/recommendations/forrest-gump", 0.65, "monthly"),
    u("/nerd-zone/recommendations/breaking-bad", 0.65, "monthly"),
    u("/nerd-zone/recommendations/the-crown", 0.65, "monthly"),
    u("/nerd-zone/recommendations/social-network", 0.65, "monthly"),
    u("/nerd-zone/recommendations/the-martian", 0.65, "monthly"),
    u("/nerd-zone/recommendations/house-of-cards", 0.65, "monthly"),
    u("/nerd-zone/recommendations/black-mirror", 0.65, "monthly"),
    u("/nerd-zone/recommendations/kings-speech", 0.65, "monthly"),
    u("/nerd-zone/recommendations/oppenheimer", 0.65, "monthly"),

    // ── Vocabulary ────────────────────────────────────────────────────────
    u("/vocabulary/a1", 0.8, "monthly"),
    u("/vocabulary/a2", 0.8, "monthly"),
    u("/vocabulary/b1", 0.8, "monthly"),
    u("/vocabulary/b2", 0.8, "monthly"),
    u("/vocabulary/c1", 0.8, "monthly"),
    u("/vocabulary/a1/animals", 0.7, "monthly"),
    u("/vocabulary/a1/at-the-cafe", 0.7, "monthly"),
    u("/vocabulary/a1/my-body", 0.7, "monthly"),
    u("/vocabulary/a1/my-family", 0.7, "monthly"),
    u("/vocabulary/a2/around-the-town", 0.7, "monthly"),
    u("/vocabulary/a2/at-the-restaurant", 0.7, "monthly"),
    u("/vocabulary/a2/clothes-and-shopping", 0.7, "monthly"),
    u("/vocabulary/a2/my-weekend", 0.7, "monthly"),
    u("/vocabulary/b1/city-life", 0.7, "monthly"),
    u("/vocabulary/b1/health-and-fitness", 0.7, "monthly"),
    u("/vocabulary/b1/job-interview", 0.7, "monthly"),
    u("/vocabulary/b1/travel-plans", 0.7, "monthly"),
    u("/vocabulary/b2/business-meeting", 0.7, "monthly"),
    u("/vocabulary/b2/environment", 0.7, "monthly"),
    u("/vocabulary/b2/media-and-technology", 0.7, "monthly"),
    u("/vocabulary/b2/social-issues", 0.7, "monthly"),
    u("/vocabulary/c1/academic-debate", 0.7, "monthly"),
    u("/vocabulary/c1/economic-challenges", 0.7, "monthly"),
    u("/vocabulary/c1/formal-english", 0.7, "monthly"),
    u("/vocabulary/c1/idioms-and-phrases", 0.7, "monthly"),

    // ── Tenses ────────────────────────────────────────────────────────────
    u("/tenses/present-simple", 0.8, "monthly"),
    u("/tenses/present-simple/to-be", 0.7, "monthly"),
    u("/tenses/present-simple/do-dont-do-i", 0.7, "monthly"),
    u("/tenses/present-simple/fill-in-blank", 0.7, "monthly"),
    u("/tenses/present-simple/quiz", 0.7, "monthly"),
    u("/tenses/present-simple/sentence-builder", 0.7, "monthly"),
    u("/tenses/present-simple/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/present-simple/ps-vs-pc", 0.7, "monthly"),
    u("/tenses/present-simple/ps-pc-advanced", 0.7, "monthly"),
    u("/tenses/present-continuous", 0.8, "monthly"),
    u("/tenses/present-continuous/ing-forms", 0.7, "monthly"),
    u("/tenses/present-continuous/stative-verbs", 0.7, "monthly"),
    u("/tenses/present-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/present-continuous/quiz", 0.7, "monthly"),
    u("/tenses/present-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/present-continuous/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/present-continuous/ps-vs-pc", 0.7, "monthly"),
    u("/tenses/present-continuous/ps-pc-advanced", 0.7, "monthly"),
    u("/tenses/present-perfect", 0.8, "monthly"),
    u("/tenses/present-perfect/have-has", 0.7, "monthly"),
    u("/tenses/present-perfect/for-since", 0.7, "monthly"),
    u("/tenses/present-perfect/irregular-participles", 0.7, "monthly"),
    u("/tenses/present-perfect/fill-in-blank", 0.7, "monthly"),
    u("/tenses/present-perfect/quiz", 0.7, "monthly"),
    u("/tenses/present-perfect/sentence-builder", 0.7, "monthly"),
    u("/tenses/present-perfect/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/present-perfect/pp-vs-ps", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous", 0.8, "monthly"),
    u("/tenses/present-perfect-continuous/have-been-ing", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/for-since-duration", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/quiz", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/pp-vs-ppc", 0.7, "monthly"),
    u("/tenses/present-perfect-continuous/all-present-tenses", 0.7, "monthly"),
    u("/tenses/past-simple", 0.8, "monthly"),
    u("/tenses/past-simple/regular-past-simple", 0.7, "monthly"),
    u("/tenses/past-simple/irregular-past-simple", 0.7, "monthly"),
    u("/tenses/past-simple/did-didnt", 0.7, "monthly"),
    u("/tenses/past-simple/fill-in-blank", 0.7, "monthly"),
    u("/tenses/past-simple/quiz", 0.7, "monthly"),
    u("/tenses/past-simple/sentence-builder", 0.7, "monthly"),
    u("/tenses/past-simple/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/past-simple/ps-vs-pc", 0.7, "monthly"),
    u("/tenses/past-continuous", 0.8, "monthly"),
    u("/tenses/past-continuous/was-were-ing", 0.7, "monthly"),
    u("/tenses/past-continuous/when-while", 0.7, "monthly"),
    u("/tenses/past-continuous/interrupted-actions", 0.7, "monthly"),
    u("/tenses/past-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/past-continuous/quiz", 0.7, "monthly"),
    u("/tenses/past-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/past-continuous/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/past-continuous/ps-vs-pc", 0.7, "monthly"),
    u("/tenses/past-perfect", 0.8, "monthly"),
    u("/tenses/past-perfect/had-past-participle", 0.7, "monthly"),
    u("/tenses/past-perfect/irregular-participles", 0.7, "monthly"),
    u("/tenses/past-perfect/sequence-of-events", 0.7, "monthly"),
    u("/tenses/past-perfect/fill-in-blank", 0.7, "monthly"),
    u("/tenses/past-perfect/quiz", 0.7, "monthly"),
    u("/tenses/past-perfect/sentence-builder", 0.7, "monthly"),
    u("/tenses/past-perfect/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/past-perfect/past-perfect-vs-past-simple", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous", 0.8, "monthly"),
    u("/tenses/past-perfect-continuous/had-been-ing", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/for-since-past", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/quiz", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/pp-vs-ppc-past", 0.7, "monthly"),
    u("/tenses/past-perfect-continuous/all-past-tenses", 0.7, "monthly"),
    u("/tenses/future-simple", 0.8, "monthly"),
    u("/tenses/future-simple/will-wont", 0.7, "monthly"),
    u("/tenses/future-simple/will-vs-going-to", 0.7, "monthly"),
    u("/tenses/future-simple/predictions", 0.7, "monthly"),
    u("/tenses/future-simple/promises-offers", 0.7, "monthly"),
    u("/tenses/future-simple/fill-in-blank", 0.7, "monthly"),
    u("/tenses/future-simple/quiz", 0.7, "monthly"),
    u("/tenses/future-simple/sentence-builder", 0.7, "monthly"),
    u("/tenses/future-simple/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/be-going-to", 0.8, "monthly"),
    u("/tenses/be-going-to/am-is-are-going-to", 0.7, "monthly"),
    u("/tenses/be-going-to/evidence-predictions", 0.7, "monthly"),
    u("/tenses/be-going-to/plans-intentions", 0.7, "monthly"),
    u("/tenses/be-going-to/will-vs-going-to", 0.7, "monthly"),
    u("/tenses/be-going-to/fill-in-blank", 0.7, "monthly"),
    u("/tenses/be-going-to/quiz", 0.7, "monthly"),
    u("/tenses/be-going-to/sentence-builder", 0.7, "monthly"),
    u("/tenses/be-going-to/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/future-continuous", 0.8, "monthly"),
    u("/tenses/future-continuous/will-be-ing", 0.7, "monthly"),
    u("/tenses/future-continuous/at-future-moment", 0.7, "monthly"),
    u("/tenses/future-continuous/polite-questions", 0.7, "monthly"),
    u("/tenses/future-continuous/will-vs-will-be-ing", 0.7, "monthly"),
    u("/tenses/future-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/future-continuous/quiz", 0.7, "monthly"),
    u("/tenses/future-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/future-continuous/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/future-perfect", 0.8, "monthly"),
    u("/tenses/future-perfect/will-have-past-participle", 0.7, "monthly"),
    u("/tenses/future-perfect/by-the-time", 0.7, "monthly"),
    u("/tenses/future-perfect/irregular-participles", 0.7, "monthly"),
    u("/tenses/future-perfect/future-perfect-vs-simple", 0.7, "monthly"),
    u("/tenses/future-perfect/fill-in-blank", 0.7, "monthly"),
    u("/tenses/future-perfect/quiz", 0.7, "monthly"),
    u("/tenses/future-perfect/sentence-builder", 0.7, "monthly"),
    u("/tenses/future-perfect/spot-the-mistake", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous", 0.8, "monthly"),
    u("/tenses/future-perfect-continuous/will-have-been-ing", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/for-duration-future", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/fp-vs-fpc", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/all-future-tenses", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/fill-in-blank", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/quiz", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/sentence-builder", 0.7, "monthly"),
    u("/tenses/future-perfect-continuous/spot-the-mistake", 0.7, "monthly"),

    // ── Reading ───────────────────────────────────────────────────────────
    u("/reading/a1", 0.8, "monthly"),
    u("/reading/a2", 0.8, "monthly"),
    u("/reading/b1", 0.8, "monthly"),
    u("/reading/b2", 0.8, "monthly"),
    u("/reading/c1", 0.8, "monthly"),
    u("/reading/a1/four-friends", 0.7, "monthly"),
    u("/reading/a1/at-the-market", 0.7, "monthly"),
    u("/reading/a1/my-school-day", 0.7, "monthly"),
    u("/reading/a2/a-weekend-trip", 0.7, "monthly"),
    u("/reading/a2/city-or-country", 0.7, "monthly"),
    u("/reading/a2/pen-pals", 0.7, "monthly"),
    u("/reading/b1/digital-lives", 0.7, "monthly"),
    u("/reading/b1/the-slow-travel-movement", 0.7, "monthly"),
    u("/reading/b1/work-from-home", 0.7, "monthly"),
    u("/reading/b2/the-gig-economy", 0.7, "monthly"),
    u("/reading/b2/changing-cities", 0.7, "monthly"),
    u("/reading/b2/the-psychology-of-habits", 0.7, "monthly"),
    u("/reading/c1/rethinking-intelligence", 0.7, "monthly"),
    u("/reading/c1/language-and-thought", 0.7, "monthly"),
    u("/reading/c1/the-attention-economy", 0.7, "monthly"),

    // ── Listening ─────────────────────────────────────────────────────────
    u("/listening/a1", 0.8, "monthly"),
    u("/listening/a2", 0.8, "monthly"),
    u("/listening/b1", 0.8, "monthly"),
    u("/listening/b2", 0.8, "monthly"),
    u("/listening/b2/work-life-balance", 0.7, "monthly"),
    u("/listening/c1", 0.8, "monthly"),
    u("/listening/c1/ethics-of-ai-art", 0.7, "monthly"),

    // ── Tests ─────────────────────────────────────────────────────────────
    u("/tests/grammar", 0.8, "monthly"),
    u("/tests/tenses", 0.8, "monthly"),
    u("/tests/vocabulary", 0.8, "monthly"),
  ];
}
