import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const FUTPERFCONT_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "By 2030 she ___ been teaching for 20 years.", options: ["will have", "will has", "would have", "will be"], answer: 0 },
  { q: "He will have been ___ for three hours by noon.", options: ["wait", "waits", "waited", "waiting"], answer: 3 },
  { q: "By the time you arrive, I ___ have been cooking for two hours.", options: ["will", "would", "shall", "am going to"], answer: 0 },
  { q: "She ___ have been working here for a decade by next June.", options: ["will", "would", "shall", "is going to"], answer: 0 },
  { q: "Will they have been ___ long when we meet?", options: ["travel", "travels", "travelled", "travelling"], answer: 3 },
  { q: "By Friday, we ___ been driving for three days.", options: ["will has", "will have", "would has", "shall has"], answer: 1 },
  { q: "She won't have been ___ here for very long.", options: ["live", "lives", "lived", "living"], answer: 3 },
  { q: "___ he have been waiting long by the time you arrive?", options: ["Would", "Will", "Shall", "Is"], answer: 1 },
  { q: "By next year, I ___ have been studying French for five years.", options: ["will", "would", "shall", "am"], answer: 0 },
  { q: "They ___ have been building that bridge for two years by March.", options: ["will", "shall", "would", "are going to"], answer: 0 },
  { q: "By the end of the film, they ___ have been watching for three hours.", options: ["will", "would", "shall", "are"], answer: 0 },
  { q: "I will have been ___ this project for six months by Thursday.", options: ["manage", "manages", "managed", "managing"], answer: 3 },
  { q: "By the time she retires, she ___ have been nursing for 30 years.", options: ["will", "would", "shall", "is going to"], answer: 0 },
  { q: "\"Will you have been waiting long?\" — \"Yes, I ___.\"", options: ["will", "shall", "would", "have"], answer: 0 },
  { q: "He won't ___ been sleeping well — look at those dark circles.", options: ["have", "has", "had", "be"], answer: 0 },
  { q: "By next month, they ___ have been renovating the house for a year.", options: ["will", "would", "shall", "are"], answer: 0 },
  { q: "She ___ have been running for an hour by the time she reaches the park.", options: ["will", "would", "shall", "is"], answer: 0 },
  { q: "Will he have been ___ there for long?", options: ["work", "works", "worked", "working"], answer: 3 },
  { q: "By the time the contract ends, we ___ have been collaborating for three years.", options: ["will", "would", "shall", "are going to"], answer: 0 },
  { q: "By 9 pm, she will ___ been reading for four hours.", options: ["have", "has", "had", "be"], answer: 0 },
];

export const FUTPERFCONT_PDF_CONFIG: LessonPDFConfig = {
  title: "Future Perfect Continuous",
  subtitle: "Duration up to a future point — 4 exercises + answer key",
  level: "C1",
  keyRule: "Subject + will have been + verb-ing  →  By 2030 she will have been teaching for 20 years.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Complete with will have been + the -ing form of the verb in brackets.",
      hint: "will have been + verb-ing",
      questions: [
        "By next year, she ___ (teach) for ten years.",
        "By Friday, we ___ (drive) for three days.",
        "By 9 pm, I ___ (work) for eight hours.",
        "By the time he retires, he ___ (manage) the team for twenty years.",
        "By March, they ___ (build) that bridge for two years.",
        "By the end of the film, we ___ (watch) for three hours.",
        "By next month, she ___ (study) French for six months.",
        "By the time you arrive, I ___ (cook) for two hours.",
        "By 2030, he ___ (run) the company for fifteen years.",
        "By the end of the conference, they ___ (present) for six hours.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the negative form: won't have been + verb-ing.",
      questions: [
        "She ___ (live) here for long when they move her again.",
        "I ___ (sleep) well by the time the alarm goes off.",
        "He ___ (exercise) for more than two weeks — he started yesterday.",
        "They ___ (work) together for long before the project ends.",
        "We ___ (wait) for hours — the meeting starts soon.",
        "She ___ (travel) far — the flight is only two hours.",
        "He ___ (study) long enough to pass the exam.",
        "It ___ (rain) for long — the forecast shows only an hour.",
        "They ___ (collaborate) for more than a year by the deadline.",
        "I ___ (run) long enough to burn many calories.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write questions with Will + subject + have been + verb-ing.",
      questions: [
        "___ she ___ (wait) long by the time we arrive?",
        "___ they ___ (renovate) the house for a year by next month?",
        "___ he ___ (work) there for a decade by 2030?",
        "___ you ___ (study) all day by the time the exam starts?",
        "___ she ___ (travel) for many hours before she lands?",
        "___ we ___ (drive) for more than five hours by lunchtime?",
        "___ he ___ (teach) here for thirty years when he retires?",
        "___ they ___ (build) this tunnel for ten years by completion?",
        "___ I ___ (cook) long enough for the food to be ready?",
        "___ she ___ (practise) for months by the time of the concert?",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Future Perfect or Future Perfect Continuous? Write the correct form.",
      questions: [
        "By 6 pm, she ___ (finish) the report. (focus: completion)",
        "By 6 pm, she ___ (work) on the report for five hours. (focus: duration)",
        "They ___ (build) the bridge by next year. (focus: completion)",
        "They ___ (build) the bridge for three years by next year. (focus: duration)",
        "He ___ (read) 50 books by the end of the year. (focus: completion)",
        "He ___ (read) for two hours by the time you call. (focus: duration)",
        "I ___ (save) enough money by summer. (focus: completion)",
        "I ___ (save) for two years by the time I buy the flat. (focus: duration)",
        "___ she ___ (finish) her thesis by June? (focus: completion)",
        "___ they ___ (wait) long by the time we get there? (focus: duration)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — will have been + verb-ing",
      answers: [
        "will have been teaching", "will have been driving", "will have been working",
        "will have been managing", "will have been building", "will have been watching",
        "will have been studying", "will have been cooking", "will have been running", "will have been presenting",
      ],
    },
    {
      exercise: 2,
      subtitle: "Medium — negative won't have been + verb-ing",
      answers: [
        "won't have been living", "won't have been sleeping", "won't have been exercising",
        "won't have been working", "won't have been waiting", "won't have been travelling",
        "won't have been studying", "won't have been raining", "won't have been collaborating", "won't have been running",
      ],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions",
      answers: [
        "Will she have been waiting long?", "Will they have been renovating for a year?",
        "Will he have been working there for a decade?", "Will you have been studying all day?",
        "Will she have been travelling for many hours?", "Will we have been driving for more than five hours?",
        "Will he have been teaching here for thirty years?", "Will they have been building this tunnel for ten years?",
        "Will I have been cooking long enough?", "Will she have been practising for months?",
      ],
    },
    {
      exercise: 4,
      subtitle: "Hard — FP vs FPC",
      answers: [
        "will have finished", "will have been working", "will have built", "will have been building",
        "will have read", "will have been reading", "will have saved", "will have been saving",
        "Will she have finished?", "Will they have been waiting long?",
      ],
    },
  ],
};
