import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const PP_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "She ___ finished her homework.", options: ["have", "has", "is", "are"], answer: 1 },
  { q: "I ___ visited Paris twice.", options: ["has", "have", "am", "was"], answer: 1 },
  { q: "They ___ lived here for ten years.", options: ["has", "is", "have", "are"], answer: 2 },
  { q: "He ___ just left the office.", options: ["have", "has", "had", "is"], answer: 1 },
  { q: "We ___ already eaten lunch.", options: ["has", "is", "are", "have"], answer: 3 },
  { q: "___ she ever been to Australia?", options: ["Have", "Did", "Was", "Has"], answer: 3 },
  { q: "I have ___ been to China. (not at any time)", options: ["ever", "already", "never", "just"], answer: 2 },
  { q: "She hasn't called me ___.", options: ["still", "already", "yet", "never"], answer: 2 },
  { q: "They have lived there ___ five years.", options: ["since", "ago", "for", "in"], answer: 2 },
  { q: "I haven't seen him ___ last Monday.", options: ["for", "ago", "yet", "since"], answer: 3 },
  { q: "She ___ called me yet.", options: ["haven't", "hasn't", "didn't", "isn't"], answer: 1 },
  { q: "I ___ seen that film before.", options: ["hasn't", "didn't", "haven't", "wasn't"], answer: 2 },
  { q: "Have you done your homework ___?", options: ["since", "just", "ever", "yet"], answer: 3 },
  { q: "He has ___ eaten — he's not hungry.", options: ["yet", "since", "already", "never"], answer: 2 },
  { q: "I ___ (see) that film last week.", options: ["have seen", "saw", "see", "had seen"], answer: 1 },
  { q: "___ you ever ridden a horse?", options: ["Did", "Have", "Had", "Were"], answer: 1 },
  { q: "She has ___ left — she just walked out.", options: ["yet", "already", "just", "never"], answer: 2 },
  { q: "go → past participle", options: ["went", "goed", "gone", "go"], answer: 2 },
  { q: "write → past participle", options: ["wrote", "written", "writed", "writ"], answer: 1 },
  { q: "How long ___ she lived here?", options: ["did", "does", "has", "is"], answer: 2 },
];

export const PP_PDF_CONFIG: LessonPDFConfig = {
  title: "Present Perfect",
  subtitle: "Connect past to present — 4 exercises + answer key",
  level: "B1",
  keyRule: "Subject + have/has + past participle  →  She has lived here for 5 years. / I have never eaten sushi.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Write the affirmative Present Perfect form: have/has + past participle.",
      hint: "have/has + past participle",
      questions: [
        "She ___ (finish) her homework.",
        "I ___ (visit) Paris twice.",
        "They ___ (live) here for ten years.",
        "He ___ (just / leave) the office.",
        "We ___ (already / eat) lunch.",
        "The film ___ (start).",
        "You ___ (do) a great job.",
        "My parents ___ (go) to Spain.",
        "It ___ (be) very cold this week.",
        "The children ___ (never / try) sushi.",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the negative Present Perfect form: haven't / hasn't + past participle.",
      questions: [
        "She ___ (call) me yet.",
        "I ___ (see) that film.",
        "They ___ (finish) the project yet.",
        "He ___ (eat) anything today.",
        "We ___ (be) to Japan.",
        "It ___ (rain) for weeks.",
        "You ___ (answer) my question.",
        "My sister ___ (arrive) yet.",
        "The results ___ (be) published yet.",
        "He ___ (speak) to her since Monday.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write Present Perfect questions using Have or Has.",
      questions: [
        "___ she ever been to Australia?",
        "___ you finished your report?",
        "___ they ever tried Indian food?",
        "\"Have you seen him?\" — \"No, ___.\"",
        "\"Has she called?\" — \"Yes, ___.\"",
        "I have ___ been to China. (not at any time)",
        "\"Have they arrived?\" — \"Yes, ___.\"",
        "___ he ever eaten octopus?",
        "She has ___ left — she just walked out.",
        "Have you finished ___ or are you still working?",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Mixed: choose have/has, write PP form, or choose for/since/already/yet.",
      questions: [
        "I ___ (just / finish) the book.",
        "She ___ (work) here since 2019.",
        "We ___ to Rome last summer. (go — which tense?)",
        "Have you done your homework ___? (yet/already)",
        "He has ___ eaten — he's not hungry. (yet/already)",
        "I ___ meet her at a party in 2021. (which tense?)",
        "They have lived in London ___ five years. (for/since)",
        "___ you ever ridden a horse? (Have/Did)",
        "She ___ her keys yesterday. (has lost / lost)",
        "I haven't seen him ___ last Monday. (for/since)",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — affirmative have/has + PP",
      answers: ["has finished", "have visited", "have lived", "has just left", "have already eaten", "has started", "have done", "have gone", "has been", "have never tried"],
    },
    {
      exercise: 2,
      subtitle: "Medium — negative haven't/hasn't + PP",
      answers: ["hasn't called", "haven't seen", "haven't finished", "hasn't eaten", "haven't been", "hasn't rained", "haven't answered", "hasn't arrived", "haven't been", "hasn't spoken"],
    },
    {
      exercise: 3,
      subtitle: "Medium — questions Have/Has?",
      answers: ["Has", "Have", "Have", "I haven't", "she has", "never", "they have", "Has", "just", "yet"],
    },
    {
      exercise: 4,
      subtitle: "Hard — mixed with for/since/already/yet",
      answers: ["have just finished", "has worked", "went (Past Simple)", "yet", "already", "met (Past Simple)", "for", "Have", "lost (Past Simple)", "since"],
    },
  ],
};
