// THIS FILE IS AUTOGENERATED BY PATCH. See patch instructions.
"use client";

import { useMemo, useState, useEffect } from "react";
import { useProgress } from "@/lib/useProgress";
import SpeedRound from "@/components/games/SpeedRound";
import type { SRQuestion } from "@/components/games/SpeedRound";
import AdUnit from "@/components/AdUnit";
import GrammarRecommended, { type GrammarRec } from "@/components/GrammarRecommended";
import { useIsPro } from "@/lib/ProContext";
import { generateLessonPDF } from "@/lib/generateLessonPDF";
import PDFButton from "@/components/PDFButton";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";
import { useLiveSync } from "@/lib/useLiveSync";

type MCQ = {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

type InputQ = {
  id: string;
  prompt: string; // with ____ gap
  correct: string; // normalized expected answer
  explanation: string;
};

type ExerciseSet =
  | { type: "mcq"; title: string; instructions: string; questions: MCQ[] }
  | { type: "input"; title: string; instructions: string; questions: InputQ[] };

function normalize(s: string) {
  return s.trim().toLowerCase();
}

const SPEED_QUESTIONS: SRQuestion[] = [
  { q: "He ___ tea every morning.", options: ["drink","drinks","drinking","drank"], answer: 1 },
  { q: "She ___ English at school.", options: ["study","studying","studied","studies"], answer: 3 },
  { q: "It ___ in the garden all day.", options: ["sit","sitting","sat","sits"], answer: 3 },
  { q: "He ___ TV in the evening.", options: ["watch","watches","watching","watched"], answer: 1 },
  { q: "She ___ to work by bus.", options: ["go","going","goes","gone"], answer: 2 },
  { q: "It ___ very fast.", options: ["walk","walking","walked","walks"], answer: 3 },
  { q: "He ___ his homework after school.", options: ["do","does","did","doing"], answer: 1 },
  { q: "She ___ lunch at noon.", options: ["eat","ate","eating","eats"], answer: 3 },
  { q: "He ___ a lot of books.", options: ["read","reads","reading","red"], answer: 1 },
  { q: "She ___ the piano every day.", options: ["plays","play","playing","played"], answer: 0 },
  { q: "It ___ here every winter.", options: ["snow","snows","snowing","snowed"], answer: 1 },
  { q: "He ___ to music at night.", options: ["listen","listens","listened","listening"], answer: 1 },
  { q: "She ___ her dog every morning.", options: ["walks","walk","walking","walked"], answer: 0 },
  { q: "He ___ football on Sundays.", options: ["play","playing","plays","played"], answer: 2 },
  { q: "It ___ a lot of electricity.", options: ["use","used","uses","using"], answer: 2 },
  { q: "She ___ very well in English.", options: ["write","wrote","writes","writing"], answer: 2 },
  { q: "He ___ the bus to school.", options: ["takes","take","took","taking"], answer: 0 },
  { q: "She ___ in a big office.", options: ["works","work","worked","working"], answer: 0 },
  { q: "It ___ a lot of noise.", options: ["makes","make","made","making"], answer: 0 },
  { q: "He ___ coffee with breakfast.", options: ["has","have","had","having"], answer: 0 },
];

const RECOMMENDATIONS: GrammarRec[] = [
  { title: "Present Simple (I/you/we/they)", href: "/grammar/a1/present-simple-i-you-we-they", img: "/topics/a1/present-simple-i-you-we-they.jpg", level: "A1", badge: "bg-emerald-500", reason: "The other half of Present Simple" },
  { title: "Present Simple Negative", href: "/grammar/a1/present-simple-negative", img: "/topics/a1/present-simple-negative.jpg", level: "A1", badge: "bg-emerald-500" },
  { title: "Present Simple Questions", href: "/grammar/a1/present-simple-questions", img: "/topics/a1/present-simple-questions.jpg", level: "A1", badge: "bg-emerald-500" },
];

export default function PresentSimpleHeSheItLessonClient() {
  const isPro = useIsPro();
  const [pdfLoading, setPdfLoading] = useState(false);
  const [tab, setTab] = useState<"exercises" | "explanation">("exercises");
  const [exNo, setExNo] = useState<1 | 2 | 3 | 4>(1);
  const [checked, setChecked] = useState(false);

  const sets: Record<1 | 2 | 3 | 4, ExerciseSet> = useMemo(() => {
    return {
      // EX 1: MCQ - choose correct verb form for he/she/it
      1: {
        type: "mcq",
        title: "Exercise 1 (Easy) — Choose the correct verb",
        instructions: "Choose the correct verb form for Present Simple (he / she / it).",
        questions: [
          {
            id: "e1q1",
            prompt: "He ___ tea every morning before work.",
            options: ["drink", "drinks", "drinking", "drank"],
            correctIndex: 1,
            explanation: "With he, add -s: he drinks.",
          },
          {
            id: "e1q2",
            prompt: "She ___ English at school every week.",
            options: ["study", "studies", "studied", "studying"],
            correctIndex: 1,
            explanation: "With she, add -ies: she studies.",
          },
          {
            id: "e1q3",
            prompt: "It ___ in the garden all day.",
            options: ["sit", "sits", "sat", "sitting"],
            correctIndex: 1,
            explanation: "With it, add -s: it sits.",
          },
          {
            id: "e1q4",
            prompt: "He ___ TV in the evening after dinner.",
            options: ["watch", "watches", "watched", "watching"],
            correctIndex: 1,
            explanation: "With he, add -es: he watches.",
          },
          {
            id: "e1q5",
            prompt: "She ___ to work by bus every day.",
            options: ["go", "goes", "going", "gone"],
            correctIndex: 1,
            explanation: "With she, add -es: she goes.",
          },
          {
            id: "e1q6",
            prompt: "It ___ very fast in the park.",
            options: ["walk", "walks", "walking", "walked"],
            correctIndex: 1,
            explanation: "With it, add -s: it walks.",
          },
          {
            id: "e1q7",
            prompt: "He ___ his homework after school.",
            options: ["do", "does", "doing", "did"],
            correctIndex: 1,
            explanation: "With he, add -es: he does.",
          },
          {
            id: "e1q8",
            prompt: "She ___ lunch at 12 o'clock.",
            options: ["eat", "eats", "eating", "ate"],
            correctIndex: 1,
            explanation: "With she, add -s: she eats.",
          },
          {
            id: "e1q9",
            prompt: "It ___ on the sofa in the afternoon.",
            options: ["sleep", "sleeps", "sleeping", "slept"],
            correctIndex: 1,
            explanation: "With it, add -s: it sleeps.",
          },
          {
            id: "e1q10",
            prompt: "He ___ music in his room.",
            options: ["listen", "listens", "listened", "listening"],
            correctIndex: 1,
            explanation: "With he, add -s: he listens.",
          },
        ],
      },

      // EX 2: input - type correct he/she/it verb form
      2: {
        type: "input",
        title: "Exercise 2 (Medium) — Type the correct verb",
        instructions: "Type the correct verb form for Present Simple (he / she / it).",
        questions: [
          {
            id: "e2q1",
            prompt: "He ___ in a big city. (live)",
            correct: "lives",
            explanation: "With he, add -s: he lives.",
          },
          {
            id: "e2q2",
            prompt: "She ___ in a hospital. (work)",
            correct: "works",
            explanation: "With she, add -s: she works.",
          },
          {
            id: "e2q3",
            prompt: "It ___ at 7 o'clock every morning. (start)",
            correct: "starts",
            explanation: "With it, add -s: it starts.",
          },
          {
            id: "e2q4",
            prompt: "He ___ football with his friends. (play)",
            correct: "plays",
            explanation: "With he, add -s: he plays.",
          },
          {
            id: "e2q5",
            prompt: "She ___ a glass of water every day. (drink)",
            correct: "drinks",
            explanation: "With she, add -s: she drinks.",
          },
          {
            id: "e2q6",
            prompt: "It ___ a lot of noise at night. (make)",
            correct: "makes",
            explanation: "With it, add -s: it makes.",
          },
          {
            id: "e2q7",
            prompt: "He ___ his hands before lunch. (wash)",
            correct: "washes",
            explanation: "With he, add -es: he washes.",
          },
          {
            id: "e2q8",
            prompt: "She ___ books in the evening. (read)",
            correct: "reads",
            explanation: "With she, add -s: she reads.",
          },
          {
            id: "e2q9",
            prompt: "It ___ in the kitchen every morning. (sit)",
            correct: "sits",
            explanation: "With it, add -s: it sits.",
          },
          {
            id: "e2q10",
            prompt: "He ___ Italian and English. (speak)",
            correct: "speaks",
            explanation: "With he, add -s: he speaks.",
          },
        ],
      },

      // EX 3: MCQ - mixed routines, distractors with base forms
      3: {
        type: "mcq",
        title: "Exercise 3 (Harder) — Pick the correct Present Simple form",
        instructions: "Choose the correct verb form for he / she / it.",
        questions: [
          {
            id: "e3q1",
            prompt: "She ___ to school by bus.",
            options: ["go", "goes", "going", "gone"],
            correctIndex: 1,
            explanation: "With she, add -es: she goes.",
          },
          {
            id: "e3q2",
            prompt: "It ___ breakfast at 8 o'clock.",
            options: ["eat", "eats", "eating", "ate"],
            correctIndex: 1,
            explanation: "With it, add -s: it eats.",
          },
          {
            id: "e3q3",
            prompt: "He ___ his homework after dinner.",
            options: ["does", "do", "doing", "did"],
            correctIndex: 0,
            explanation: "With he, add -es: he does.",
          },
          {
            id: "e3q4",
            prompt: "She ___ TV with her family.",
            options: ["watch", "watches", "watched", "watching"],
            correctIndex: 1,
            explanation: "With she, add -es: she watches.",
          },
          {
            id: "e3q5",
            prompt: "It ___ in the park every morning.",
            options: ["walk", "walks", "walking", "walked"],
            correctIndex: 1,
            explanation: "With it, add -s: it walks.",
          },
          {
            id: "e3q6",
            prompt: "He ___ pizza on Fridays.",
            options: ["eat", "eats", "eating", "ate"],
            correctIndex: 1,
            explanation: "With he, add -s: he eats.",
          },
          {
            id: "e3q7",
            prompt: "She ___ her friends after school.",
            options: ["meet", "meets", "meeting", "met"],
            correctIndex: 1,
            explanation: "With she, add -s: she meets.",
          },
          {
            id: "e3q8",
            prompt: "It ___ at 6 o'clock every day.",
            options: ["finish", "finishes", "finished", "finishing"],
            correctIndex: 1,
            explanation: "With it, add -es: it finishes.",
          },
          {
            id: "e3q9",
            prompt: "He ___ coffee in the morning.",
            options: ["drinks", "drink", "drank", "drinking"],
            correctIndex: 0,
            explanation: "With he, add -s: he drinks.",
          },
          {
            id: "e3q10",
            prompt: "She ___ music in her room.",
            options: ["listen", "listens", "listened", "listening"],
            correctIndex: 1,
            explanation: "With she, add -s: she listens.",
          },
        ],
      },

      // EX 4: input - complete full sentences
      4: {
        type: "input",
        title: "Exercise 4 (Challenge) — Complete the sentences",
        instructions: "Complete the sentences in Present Simple (he / she / it).",
        questions: [
          {
            id: "e4q1",
            prompt: "He ___ to work every morning.",
            correct: "goes",
            explanation: "With he, add -es: he goes.",
          },
          {
            id: "e4q2",
            prompt: "She ___ breakfast at 7 o'clock.",
            correct: "eats",
            explanation: "With she, add -s: she eats.",
          },
          {
            id: "e4q3",
            prompt: "It ___ in the sun all day.",
            correct: "sits",
            explanation: "With it, add -s: it sits.",
          },
          {
            id: "e4q4",
            prompt: "He ___ his room on Saturdays.",
            correct: "cleans",
            explanation: "With he, add -s: he cleans.",
          },
          {
            id: "e4q5",
            prompt: "She ___ her mother in the kitchen.",
            correct: "helps",
            explanation: "With she, add -s: she helps.",
          },
          {
            id: "e4q6",
            prompt: "It ___ water from the bowl.",
            correct: "drinks",
            explanation: "With it, add -s: it drinks.",
          },
          {
            id: "e4q7",
            prompt: "He ___ books every evening.",
            correct: "reads",
            explanation: "With he, add -s: he reads.",
          },
          {
            id: "e4q8",
            prompt: "She ___ to music after school.",
            correct: "listens",
            explanation: "With she, add -s: she listens.",
          },
          {
            id: "e4q9",
            prompt: "It ___ at 8 o'clock every night.",
            correct: "sleeps",
            explanation: "With it, add -s: it sleeps.",
          },
          {
            id: "e4q10",
            prompt: "He ___ his homework before dinner.",
            correct: "does",
            explanation: "With he, add -es: he does.",
          },
        ],
      },
    };
  }, []);

  // Store answers
  const [mcqAnswers, setMcqAnswers] = useState<Record<string, number | null>>({});
  const [inputAnswers, setInputAnswers] = useState<Record<string, string>>({});

  const { isLive, broadcast } = useLiveSync((payload) => {
    setMcqAnswers(payload.answers as Record<string, number | null>);
    setInputAnswers((payload as unknown as { inputAnswers: Record<string, string> }).inputAnswers ?? {});
    setChecked(payload.checked as boolean);
    setExNo(payload.exNo as 1 | 2 | 3 | 4);
  });

  const current = sets[exNo];

  const { save } = useProgress();

  useEffect(() => {
    if (checked && score) {
      save(exNo, score.percent, score.total);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [checked]);

  const score = useMemo(() => {
    if (!checked) return null;

    let correct = 0;
    let total = 0;

    if (current.type === "mcq") {
      total = current.questions.length;
      for (const q of current.questions) {
        const a = mcqAnswers[q.id];
        if (a === q.correctIndex) correct++;
      }
    } else {
      total = current.questions.length;
      for (const q of current.questions) {
        const a = normalize(inputAnswers[q.id] ?? "");
        if (a && a === normalize(q.correct)) correct++;
      }
    }

    const percent = total ? Math.round((correct / total) * 100) : 0;
    return { correct, total, percent };
  }, [checked, current, mcqAnswers, inputAnswers]);

  function resetExercise() {
    window.scrollTo({ top: 0, behavior: "smooth" });
    setChecked(false);
    setMcqAnswers({});
    setInputAnswers({});
    broadcast({ answers: {}, checked: false, exNo });
  }

  function switchExercise(n: 1 | 2 | 3 | 4) {
    window.scrollTo({ top: 0, behavior: "smooth" });
    setExNo(n);
    setChecked(false);
    setMcqAnswers({});
    setInputAnswers({});
    broadcast({ answers: {}, checked: false, exNo: n });
  }

  async function downloadPDF() {
    setPdfLoading(true);
    try {
      const config: LessonPDFConfig = {
        title: "Present Simple",
        subtitle: "He / She / It — verb endings (-s, -es, -ies) — 4 exercises + answer key",
        level: "A1",
        keyRule: "He / she / it: add -S to most verbs (drinks, reads). Add -ES after -s/-sh/-ch/-x/-o (watches, goes). Change -y → -IES (studies, flies).",
        exercises: [
          {
            number: 1, title: "Exercise 1", difficulty: "Easy",
            instruction: "Choose the correct verb form for he / she / it.",
            questions: [
              "He ___ tea every morning. (drink)",
              "She ___ English at school. (study)",
              "It ___ in the garden all day. (sit)",
              "He ___ TV in the evening. (watch)",
              "She ___ to work by bus. (go)",
              "It ___ very fast. (walk)",
              "He ___ his homework after school. (do)",
              "She ___ lunch at noon. (eat)",
              "He ___ many books. (read)",
              "She ___ the piano every day. (play)",
            ],
            hint: "add -s / -es / -ies",
          },
          {
            number: 2, title: "Exercise 2", difficulty: "Easy",
            instruction: "Choose the correct verb form.",
            questions: [
              "It ___ a lot in winter here. (snow)",
              "He ___ to music at night. (listen)",
              "She ___ her dog every morning. (walk)",
              "He ___ football on Sundays. (play)",
              "It ___ a lot of electricity. (use)",
              "She ___ very well in English. (write)",
              "He ___ the bus to school. (take)",
              "She ___ in a big office. (work)",
              "It ___ a lot of noise. (make)",
              "He ___ coffee with breakfast. (have)",
            ],
            hint: "add -s / -es / -ies",
          },
          {
            number: 3, title: "Exercise 3", difficulty: "Medium",
            instruction: "Write the correct form of the verb in brackets.",
            questions: [
              "She ___ (fly) to Paris every month for work.",
              "He ___ (wash) his car on Saturday mornings.",
              "It ___ (finish) at 6 pm every evening.",
              "She ___ (carry) a heavy bag to the office.",
              "He ___ (mix) the paint before using it.",
              "It ___ (catch) insects in the garden.",
              "She ___ (fix) computers for a living.",
              "He ___ (push) the cart around the supermarket.",
              "It ___ (buzz) all night and keeps me awake.",
              "She ___ (try) a new recipe every weekend.",
            ],
          },
          {
            number: 4, title: "Exercise 4", difficulty: "Hard",
            instruction: "Write the correct Present Simple form of the verb.",
            questions: [
              "My sister ___ (teach) maths at a local school.",
              "The cat ___ (sleep) on the sofa all afternoon.",
              "He ___ (miss) his family when he travels.",
              "She ___ (reply) to every message very quickly.",
              "The dog ___ (bark) at strangers every time.",
              "My brother ___ (wish) he could play the guitar.",
              "She ___ (pass) the school every day on her walk.",
              "The plane ___ (land) at 9 am on Thursdays.",
              "He ___ (enjoy) cooking on weekends with friends.",
              "The river ___ (flow) through the centre of town.",
            ],
          },
        ],
        answerKey: [
          { exercise: 1, subtitle: "Easy — choose correct form", answers: ["drinks","studies","sits","watches","goes","walks","does","eats","reads","plays"] },
          { exercise: 2, subtitle: "Easy — choose correct form", answers: ["snows","listens","walks","plays","uses","writes","takes","works","makes","has"] },
          { exercise: 3, subtitle: "Medium — write the form", answers: ["flies","washes","finishes","carries","mixes","catches","fixes","pushes","buzzes","tries"] },
          { exercise: 4, subtitle: "Hard — write the form", answers: ["teaches","sleeps","misses","replies","barks","wishes","passes","lands","enjoys","flows"] },
        ],
      };
      await generateLessonPDF(config);
    } finally {
      setPdfLoading(false);
    }
  }

  return (
    <div className="relative min-h-screen w-full">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-[#FFF7D9] via-white to-white" />
      <div className="pointer-events-none absolute -top-28 left-1/2 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-[#F5DA20]/20 blur-3xl" />
      <div className="relative mx-auto max-w-7xl px-6 py-10">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-slate-500">
        <a className="hover:text-slate-900 transition" href="/">Home</a>
        <span className="text-slate-300">/</span>
        <a className="hover:text-slate-900 transition" href="/grammar/a1">Grammar A1</a>
        <span className="text-slate-300">/</span>
        <span className="text-slate-700 font-medium">Present Simple (he / she / it)</span>
      </div>

      <div className="mt-4 flex flex-wrap items-start gap-3">
        <h1 className="text-3xl md:text-5xl font-black tracking-tight text-slate-900 leading-tight">
          Present Simple <span className="font-extrabold">(he / she / it)</span>
        </h1>
        <span className="mt-2 inline-flex items-center rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700 border border-emerald-200">
          A1
        </span>
      </div>

      <p className="mt-3 max-w-3xl text-slate-700">
        Learn how to use the Present Simple for <b>he</b>, <b>she</b>, and <b>it</b>. Practice with 4 easy exercises!
      </p>

      {/* Layout: left col + center content + right col */}
      <div className="mt-10 grid gap-8 lg:grid-cols-[300px_1fr_300px]">
        {/* Left column */}
        {isPro ? (
          <div className="">
            <SpeedRound gameId="grammar-a1-present-simple-he-she-it" subject="Present Simple (he/she/it)" questions={SPEED_QUESTIONS} variant="sidebar" />
          </div>
        ) : (
          <AdUnit variant="sidebar-dark" />

        )}

        {/* Center */}
        <section className="rounded-2xl border border-black/10 bg-white/70 backdrop-blur overflow-hidden">
          {/* Tabs */}
          <div className="flex items-center gap-2 border-b border-black/10 bg-white/60 p-3">
            <button
              onClick={() => setTab("exercises")}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition ${
                tab === "exercises" ? "bg-[#F5DA20] text-black" : "text-slate-700 hover:bg-black/5"
              }`}
            >
              Exercises
            </button>
            <button
              onClick={() => setTab("explanation")}
              className={`rounded-xl px-4 py-2 text-sm font-bold transition ${
                tab === "explanation" ? "bg-[#F5DA20] text-black" : "text-slate-700 hover:bg-black/5"
              }`}
            >
              Explanation
            </button>

            <PDFButton onDownload={downloadPDF} loading={pdfLoading} />

            <div className="ml-auto hidden sm:flex items-center gap-2 text-sm text-slate-600">
              Exercises:
              {[1, 2, 3, 4].map((n) => (
                <button
                  key={n}
                  onClick={() => switchExercise(n as 1 | 2 | 3 | 4)}
                  className={`h-9 w-9 rounded-xl border border-black/10 font-bold transition ${
                    exNo === n ? "bg-[#F5DA20] text-black" : "bg-white text-slate-800 hover:bg-black/5"
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="p-6 md:p-8">
            {tab === "exercises" ? (
              <>
                <div className="flex flex-col gap-2">
                  <h2 className="text-2xl font-black text-slate-900">{current.title}</h2>
                  <p className="text-slate-700">{current.instructions}</p>

                  {/* Mobile exercise buttons */}
                  <div className="mt-2 flex sm:hidden items-center gap-2 text-sm text-slate-600">
                    <span>Exercises:</span>
                    {[1, 2, 3, 4].map((n) => (
                      <button
                        key={n}
                        onClick={() => switchExercise(n as 1 | 2 | 3 | 4)}
                        className={`h-9 w-9 rounded-xl border border-black/10 font-bold transition ${
                          exNo === n ? "bg-[#F5DA20] text-black" : "bg-white text-slate-800 hover:bg-black/5"
                        }`}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Questions */}
                <div className="mt-8 space-y-5">
                  {current.type === "mcq" ? (
                    current.questions.map((q, idx) => {
                      const chosen = mcqAnswers[q.id] ?? null;
                      const isCorrect = checked && chosen === q.correctIndex;
                      const isWrong = checked && chosen !== null && chosen !== q.correctIndex;
                      const noAnswer = checked && chosen === null;

                      return (
                        <div key={q.id} className="rounded-2xl border border-black/10 bg-white p-5">
                          <div className="flex items-start gap-3">
                            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-black/5 text-sm font-black text-slate-700">
                              {idx + 1}
                            </div>
                            <div className="flex-1">
                              <div className="font-bold text-slate-900">{q.prompt}</div>

                              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                                {q.options.map((opt, oi) => (
                                  <label
                                    key={oi}
                                    className={`flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2 transition ${
                                      chosen === oi
                                        ? "border-[#F5DA20] bg-[#F5DA20]/20"
                                        : "border-black/10 bg-white hover:bg-black/5"
                                    } ${checked ? "cursor-default opacity-95" : ""}`}
                                  >
                                    <input
                                      type="radio"
                                      name={q.id}
                                      disabled={checked}
                                      checked={chosen === oi}
                                      onChange={() => { setMcqAnswers((p) => { const n = { ...p, [q.id]: oi }; broadcast({ answers: n, checked, exNo }); return n; }); }}
                                    />
                                    <span className="text-slate-900">{opt}</span>
                                  </label>
                                ))}
                              </div>

                              {checked && (
                                <div className="mt-3 text-sm">
                                  {isCorrect && <div className="text-emerald-700 font-semibold">✅ Correct</div>}
                                  {isWrong && <div className="text-red-700 font-semibold">❌ Wrong</div>}
                                  {noAnswer && <div className="text-amber-700 font-semibold">⚠ No answer</div>}

                                  <div className="mt-2 text-slate-700">
                                    <b className="text-slate-900">Correct:</b> {q.options[q.correctIndex]} — {q.explanation}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })
                  ) : (
                    current.questions.map((q, idx) => {
                      const val = inputAnswers[q.id] ?? "";
                      const answered = normalize(val) !== "";
                      const isCorrect = checked && answered && normalize(val) === normalize(q.correct);
                      const noAnswer = checked && !answered;
                      const wrong = checked && answered && !isCorrect;

                      return (
                        <div key={q.id} className="rounded-2xl border border-black/10 bg-white p-5">
                          <div className="flex items-start gap-3">
                            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-black/5 text-sm font-black text-slate-700">
                              {idx + 1}
                            </div>

                            <div className="flex-1">
                              <div className="font-bold text-slate-900">{q.prompt}</div>

                              <div className="mt-3 flex items-center gap-3">
                                <input
                                  value={val}
                                  disabled={checked}
                                  onChange={(e) => setInputAnswers((p) => ({ ...p, [q.id]: e.target.value }))}
                                  placeholder="Type here…"
                                  className="w-full max-w-xs rounded-xl border border-black/10 bg-white px-4 py-3 text-slate-900 placeholder:text-slate-400 outline-none focus:border-[#F5DA20]"
                                />
                              </div>

                              {checked && (
                                <div className="mt-3 text-sm">
                                  {isCorrect && <div className="text-emerald-700 font-semibold">✅ Correct</div>}
                                  {wrong && <div className="text-red-700 font-semibold">❌ Wrong</div>}
                                  {noAnswer && <div className="text-amber-700 font-semibold">⚠ No answer</div>}

                                  <div className="mt-2 text-slate-700">
                                    <b className="text-slate-900">Correct:</b> {q.correct} — {q.explanation}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>

                {/* Controls */}
                <div className="mt-8 space-y-4">
                  <div className="flex flex-wrap gap-3 items-center">
                    {!checked ? (
                      <button
                        onClick={() => { setChecked(true); broadcast({ answers: mcqAnswers, checked: true, exNo }); window.scrollTo({ top: 0, behavior: "smooth" }); }}
                        className="rounded-2xl bg-[#F5DA20] px-6 py-3 text-sm font-black text-black hover:opacity-90 transition shadow-sm"
                      >
                        Check Answers
                      </button>
                    ) : (
                      <button
                        onClick={resetExercise}
                        className="rounded-2xl border border-black/10 bg-white px-6 py-3 text-sm font-bold text-slate-900 hover:bg-black/5 transition"
                      >
                        Try Again
                      </button>
                    )}
                    {checked && exNo < 4 && (
                      <button
                        onClick={() => switchExercise((exNo + 1) as 1 | 2 | 3 | 4)}
                        className="rounded-2xl border border-black/10 bg-white px-6 py-3 text-sm font-bold text-slate-700 hover:bg-black/5 transition"
                      >
                        Next Exercise →
                      </button>
                    )}
                  </div>

                  {score && (
                    <div className={`rounded-2xl border p-4 ${
                      score.percent >= 80
                        ? "border-emerald-200 bg-emerald-50"
                        : score.percent >= 50
                        ? "border-amber-200 bg-amber-50"
                        : "border-red-200 bg-red-50"
                    }`}>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className={`text-3xl font-black ${
                            score.percent >= 80 ? "text-emerald-700" : score.percent >= 50 ? "text-amber-700" : "text-red-700"
                          }`}>
                            {score.percent}%
                          </div>
                          <div className="mt-0.5 text-sm text-slate-600">
                            {score.correct} out of {score.total} correct
                          </div>
                        </div>
                        <div className="text-3xl">
                          {score.percent >= 80 ? "🎉" : score.percent >= 50 ? "💪" : "📖"}
                        </div>
                      </div>
                      <div className="mt-3 h-2 w-full rounded-full bg-black/10 overflow-hidden">
                        <div
                          className={`h-2 rounded-full transition-all duration-500 ${
                            score.percent >= 80 ? "bg-emerald-500" : score.percent >= 50 ? "bg-amber-500" : "bg-red-500"
                          }`}
                          style={{ width: `${score.percent}%` }}
                        />
                      </div>
                      <div className="mt-2 text-xs text-slate-500">
                        {score.percent >= 80
                          ? "Excellent! You can move to the next exercise."
                          : score.percent >= 50
                          ? "Good effort! Try once more to improve your score."
                          : "Keep practising — review the Explanation tab and try again."}
                      </div>
                    </div>
                  )}
                </div>
              </>
            ) : (
              <Explanation />
            )}
          </div>
        </section>

        {/* Right column */}
        {isPro ? (
          <GrammarRecommended recommendations={RECOMMENDATIONS} allHref="/grammar/a1" allLabel="All A1 topics" />
        ) : (
          <AdUnit variant="sidebar-light" />

        )}
      </div>

      {/* Bottom navigation */}
      <div className="mt-10 flex items-center justify-between gap-4 border-t border-black/8 pt-8">
        <a
          href="/grammar/a1"
          className="flex items-center gap-2 rounded-2xl border border-black/10 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-black/5 transition"
        >
          ← All A1 topics
        </a>
        <a
          href="/grammar/a1/present-simple-negative"
          className="flex items-center gap-2 rounded-2xl bg-[#F5DA20] px-5 py-3 text-sm font-black text-black hover:opacity-90 transition shadow-sm"
        >
          Next: Present Simple: negative →
        </a>
      </div>
      </div>
    </div>
  );
}

function Formula({ parts }: { parts: Array<{ text: string; color?: string; dim?: boolean }> }) {
  const colors: Record<string, string> = {
    sky:    "bg-sky-100 text-sky-800 border-sky-200",
    yellow: "bg-[#FFF3A3] text-amber-800 border-amber-300",
    red:    "bg-red-100 text-red-800 border-red-200",
    violet: "bg-violet-100 text-violet-800 border-violet-200",
    green:  "bg-emerald-100 text-emerald-800 border-emerald-200",
    slate:  "bg-slate-100 text-slate-600 border-slate-200",
  };
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      {parts.map((p, i) =>
        p.dim ? (
          <span key={i} className="text-slate-400 font-bold text-sm">+</span>
        ) : (
          <span key={i} className={`rounded-lg px-2.5 py-1 text-xs font-black border ${p.color ? colors[p.color] : colors.slate}`}>
            {p.text}
          </span>
        )
      )}
    </div>
  );
}

function Ex({ en, correct = true }: { en: string; correct?: boolean }) {
  return (
    <div className={`flex items-start gap-2 rounded-xl px-3 py-2.5 ${correct ? "bg-white border border-black/8" : "bg-red-50 border border-red-100"}`}>
      <span className="text-sm shrink-0">{correct ? "✅" : "❌"}</span>
      <div className={`font-semibold text-sm ${correct ? "text-slate-900" : "text-red-700 line-through"}`}>{en}</div>
    </div>
  );
}

function Explanation() {
  return (
    <div className="space-y-8">
      {/* Title */}
      <div>
        <h2 className="text-2xl font-black text-slate-900 mb-1">Present Simple — He / She / It</h2>
        <p className="text-slate-500 text-sm">Add -s (or -es) to the verb whenever the subject is he, she, it, or any singular noun.</p>
      </div>

      {/* 3 gradient cards */}
      <div className="grid gap-4 md:grid-cols-3">
        {/* Affirmative */}
        <div className="rounded-2xl border-2 border-emerald-200 bg-gradient-to-b from-emerald-50 to-white p-4">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-lg">✅</span>
            <span className="text-sm font-black text-emerald-700 uppercase tracking-widest">Affirmative</span>
          </div>
          <Formula parts={[{ text: "he/she/it", color: "green" }, { dim: true, text: "+" }, { text: "verb+s", color: "sky" }, { dim: true, text: "+" }, { text: "rest" }]} />
          <div className="mt-3 space-y-2">
            <Ex en="He works every day." />
            <Ex en="She goes by bus." />
            <Ex en="It sleeps all day." />
          </div>
        </div>

        {/* Negative */}
        <div className="rounded-2xl border-2 border-red-200 bg-gradient-to-b from-red-50 to-white p-4">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-lg">❌</span>
            <span className="text-sm font-black text-red-700 uppercase tracking-widest">Negative</span>
          </div>
          <Formula parts={[{ text: "he/she/it", color: "green" }, { dim: true, text: "+" }, { text: "doesn't", color: "red" }, { dim: true, text: "+" }, { text: "verb" }]} />
          <div className="mt-3 space-y-2">
            <Ex en="He doesn't work on Sundays." />
            <Ex en="She doesn't eat meat." />
            <Ex en="It doesn't like water." />
          </div>
        </div>

        {/* Question */}
        <div className="rounded-2xl border-2 border-sky-200 bg-gradient-to-b from-sky-50 to-white p-4">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-lg">❓</span>
            <span className="text-sm font-black text-sky-700 uppercase tracking-widest">Question</span>
          </div>
          <Formula parts={[{ text: "Does", color: "sky" }, { dim: true, text: "+" }, { text: "he/she/it", color: "green" }, { dim: true, text: "+" }, { text: "verb ?" }]} />
          <div className="mt-3 space-y-2">
            <Ex en="Does he live here?" />
            <Ex en="Does she speak French?" />
            <Ex en="Does it work?" />
          </div>
        </div>
      </div>

      {/* Spelling rules card */}
      <div className="rounded-2xl border border-black/10 bg-white p-5">
        <div className="flex items-center gap-2 mb-4">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#F5DA20] text-sm font-black">!</span>
          <h3 className="font-black text-slate-900">Spelling rules for he/she/it forms</h3>
        </div>
        <div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3">
          <div className="rounded-xl bg-slate-50 border border-black/8 p-3">
            <div className="text-xs font-black text-slate-500 uppercase mb-2">Most verbs → +s</div>
            <div className="text-sm space-y-1 text-slate-700">
              <div>work → <b>works</b></div>
              <div>eat → <b>eats</b></div>
              <div>play → <b>plays</b></div>
            </div>
          </div>
          <div className="rounded-xl bg-slate-50 border border-black/8 p-3">
            <div className="text-xs font-black text-slate-500 uppercase mb-2">-s/-sh/-ch/-x/-o → +es</div>
            <div className="text-sm space-y-1 text-slate-700">
              <div>go → <b>goes</b></div>
              <div>watch → <b>watches</b></div>
              <div>do → <b>does</b></div>
            </div>
          </div>
          <div className="rounded-xl bg-slate-50 border border-black/8 p-3">
            <div className="text-xs font-black text-slate-500 uppercase mb-2">consonant+y → -ies / irregular</div>
            <div className="text-sm space-y-1 text-slate-700">
              <div>study → <b>studies</b></div>
              <div>fly → <b>flies</b></div>
              <div>have → <b>has</b></div>
            </div>
          </div>
        </div>
      </div>

      {/* Reference table */}
      <div className="rounded-2xl border border-black/10 bg-white p-5">
        <div className="flex items-center gap-2 mb-4">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-sky-100 text-sm font-black text-sky-700">≡</span>
          <h3 className="font-black text-slate-900">5 common verbs — base vs he/she/it form</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-black/10">
                <th className="text-left py-2 pr-4 font-black text-slate-700">Base form</th>
                <th className="text-left py-2 pr-4 font-black text-slate-700">He/she/it form</th>
                <th className="text-left py-2 font-black text-slate-700">Example</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              <tr><td className="py-2 pr-4 text-slate-700">go</td><td className="py-2 pr-4 font-bold text-sky-700">goes</td><td className="py-2 text-slate-600 italic">She goes to work by train.</td></tr>
              <tr><td className="py-2 pr-4 text-slate-700">watch</td><td className="py-2 pr-4 font-bold text-sky-700">watches</td><td className="py-2 text-slate-600 italic">He watches TV after dinner.</td></tr>
              <tr><td className="py-2 pr-4 text-slate-700">study</td><td className="py-2 pr-4 font-bold text-sky-700">studies</td><td className="py-2 text-slate-600 italic">She studies every evening.</td></tr>
              <tr><td className="py-2 pr-4 text-slate-700">have</td><td className="py-2 pr-4 font-bold text-sky-700">has</td><td className="py-2 text-slate-600 italic">He has a new car.</td></tr>
              <tr><td className="py-2 pr-4 text-slate-700">work</td><td className="py-2 pr-4 font-bold text-sky-700">works</td><td className="py-2 text-slate-600 italic">It works perfectly.</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Amber warning */}
      <div className="rounded-xl bg-amber-50 border border-amber-200 px-4 py-3 text-sm text-amber-800">
        <b>⚠ Key point:</b> After <b>doesn't</b> and <b>does</b>, the main verb is always the <b>base form</b> — never add -s! It&apos;s <em>She doesn't work</em>, not <span className="line-through">She doesn't works</span>. The -s lives inside "doesn't", not on the main verb.
      </div>
    </div>
  );
}