import type { SRQuestion } from "@/components/games/SpeedRound";
import type { LessonPDFConfig } from "@/lib/generateLessonPDF";

export const BGT_SPEED_QUESTIONS: SRQuestion[] = [
  { q: "I ___ going to call you later.", options: ["am", "is", "are", "be"], answer: 0 },
  { q: "She ___ going to study abroad next year.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "They ___ going to move to a new city.", options: ["am", "is", "are", "be"], answer: 2 },
  { q: "Look at those clouds! It ___ going to rain.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "We ___ going to visit Rome this summer.", options: ["am", "is", "are", "be"], answer: 2 },
  { q: "___ he going to apply for the job?", options: ["Am", "Is", "Are", "Does"], answer: 1 },
  { q: "She ___ going to leave — she's already packed.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "I ___ not going to accept that offer.", options: ["am", "is", "are", "be"], answer: 0 },
  { q: "Watch out! He ___ going to fall!", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "They ___ going to announce the results tonight.", options: ["am", "is", "are", "be"], answer: 2 },
  { q: "___ you going to come to the party?", options: ["Am", "Is", "Are", "Do"], answer: 2 },
  { q: "She isn't ___ to change her mind.", options: ["go", "going", "goes", "gone"], answer: 1 },
  { q: "He ___ going to buy a new laptop next week.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "\"Is it going to rain?\" — \"Yes, ___.\"", options: ["it is", "it does", "it rains", "it are"], answer: 0 },
  { q: "\"Are they going to stay?\" — \"No, ___.\"", options: ["they don't", "they aren't", "they isn't", "they not"], answer: 1 },
  { q: "The team ___ going to win — they're the best!", options: ["am", "are", "is", "be"], answer: 2 },
  { q: "We ___ going to paint the house this weekend.", options: ["is", "am", "are", "be"], answer: 2 },
  { q: "I'm going to ___ harder this semester.", options: ["studies", "studied", "study", "studying"], answer: 2 },
  { q: "Look! That vase ___ going to fall!", options: ["am", "are", "is", "be"], answer: 2 },
  { q: "___ she going to travel alone?", options: ["Am", "Is", "Are", "Do"], answer: 1 },
];

export const BGT_PDF_CONFIG: LessonPDFConfig = {
  title: "Be Going To",
  subtitle: "Plans, intentions & evidence predictions — 4 exercises + answer key",
  level: "A2",
  keyRule: "Subject + am/is/are + going to + base verb  →  She is going to study. / It is going to rain.",
  exercises: [
    {
      number: 1,
      title: "Exercise 1",
      difficulty: "Easy",
      instruction: "Complete the sentences with am / is / are + going to.",
      hint: "am (I) · is (he/she/it) · are (you/we/they)",
      questions: [
        "She ___ going to leave tomorrow. (is / are / am)",
        "I ___ going to visit my parents this weekend. (am / is / are)",
        "They ___ going to play football on Saturday. (are / am / is)",
        "He ___ going to study medicine. (is / am / are)",
        "We ___ going to travel to Spain. (are / is / am)",
        "Look! It ___ going to rain. (is / are / am)",
        "You ___ going to love this film! (are / am / is)",
        "My parents ___ going to move to the countryside. (are / is / am)",
        "The children ___ going to perform at the concert. (are / am / is)",
        "She ___ going to start a new job next month. (is / are / am)",
      ],
    },
    {
      number: 2,
      title: "Exercise 2",
      difficulty: "Medium",
      instruction: "Write the negative form: am not / isn't / aren't + going to.",
      questions: [
        "She ___ (come) to the party tonight.",
        "I ___ (accept) their offer.",
        "They ___ (wait) any longer.",
        "He ___ (change) his plans.",
        "We ___ (stay) for dinner.",
        "It ___ (be) easy.",
        "You ___ (need) an umbrella — it's sunny.",
        "The project ___ (finish) on time.",
        "She ___ (forget) this day.",
        "The kids ___ (eat) their vegetables.",
      ],
    },
    {
      number: 3,
      title: "Exercise 3",
      difficulty: "Medium",
      instruction: "Write questions with Am / Is / Are + going to.",
      questions: [
        "___ she going to leave? (leave)",
        "___ you going to apply? (apply)",
        "___ they going to join us? (join)",
        "___ he going to call back? (call)",
        "___ it going to rain? (rain)",
        "___ I going to pass the exam? (pass)",
        "___ we going to be late? (be)",
        "___ she going to travel alone? (travel)",
        "___ he going to retire soon? (retire)",
        "___ they going to announce the results? (announce)",
      ],
    },
    {
      number: 4,
      title: "Exercise 4",
      difficulty: "Hard",
      instruction: "Evidence predictions. Write the correct be going to form based on the visible situation.",
      questions: [
        "Look at those clouds! It ___ (rain) soon.",
        "Watch out! That ladder ___ (fall) — it's leaning badly.",
        "She's very pale. I think she ___ (faint).",
        "Look at that car! It ___ (crash) into the wall!",
        "He's running very fast. He ___ (win) the race!",
        "The sky is orange and red. It ___ (be) a beautiful sunset.",
        "Their car is making a strange noise. It ___ (break down).",
        "She's practising every day. She ___ (improve) quickly.",
        "Look — the ice on the road! You ___ (slip) if you're not careful.",
        "The river level is rising. It ___ (flood) the valley.",
      ],
    },
  ],
  answerKey: [
    {
      exercise: 1,
      subtitle: "Easy — am / is / are + going to",
      answers: ["is", "am", "are", "is", "are", "is", "are", "are", "are", "is"],
    },
    {
      exercise: 2,
      subtitle: "Medium — negative going to",
      answers: [
        "isn't going to come", "am not going to accept", "aren't going to wait",
        "isn't going to change", "aren't going to stay", "isn't going to be",
        "aren't going to need", "isn't going to finish", "isn't going to forget", "aren't going to eat",
      ],
    },
    {
      exercise: 3,
      subtitle: "Medium — going to questions",
      answers: [
        "Is she going to leave?", "Are you going to apply?", "Are they going to join us?",
        "Is he going to call back?", "Is it going to rain?", "Am I going to pass the exam?",
        "Are we going to be late?", "Is she going to travel alone?", "Is he going to retire soon?", "Are they going to announce the results?",
      ],
    },
    {
      exercise: 4,
      subtitle: "Hard — evidence predictions",
      answers: [
        "is going to rain", "is going to fall", "is going to faint", "is going to crash",
        "is going to win", "is going to be", "is going to break down", "is going to improve",
        "are going to slip", "is going to flood",
      ],
    },
  ],
};
